// ─── MapleSheet Co. — central data & config ─────────────────────
// Lino: this is the ONE file you'll edit most often.

export const CONFIG = {
  shopUrl: "https://maplesheetco.etsy.com",
  calcUrl: "https://claude.ai/public/artifacts/1620ddd7-219c-4052-8557-2a8c6d63e7fb",
  email: "hello@maplesheet.ca",
  xUrl: "https://x.com/MapleSheetCo",
  youtubeUrl: "https://www.youtube.com/@MapleSheetCo", // ← Lino: confirm handle
  affiliateUrl: "https://payhip.com/auth/register/af6a64b512341ea",
  promoCode: "MAPLE25",
  promoText: "25% off everything with code MAPLE25",
  freeToolUrl: "https://claude.ai/public/artifacts/1620ddd7-219c-4052-8557-2a8c6d63e7fb",
  // Web3Forms: create a free access key at https://web3forms.com (enter hello@maplesheet.ca)
  // and paste it below to activate the contact + newsletter forms:
  web3formsKey: "88c72f3b-a279-446a-871b-91d29a308bc5",
};

export const B = {
  black: "#131312",
  black2: "#1B1B1A",
  black3: "#232322",
  white: "#FFFFFF",
  red: "#CC0000",
  redHover: "#DC2626",
  gray: "#5C5C5B",
  grayLight: "#9C9C9A",
  line: "#2E2E2C",
  yellow: "#FCD34D",
};

export const PRODUCTS = [
  { name: "TFSA Tracker", tag: "TFSA", price: 9.99, url: "https://www.etsy.com/listing/4529134188", directUrl: "https://payhip.com/b/rb9SR", desc: "Live prices, ACB, dividends, tax-free growth" },
  { name: "RRSP Tracker", tag: "RRSP", price: 9.99, url: "https://www.etsy.com/listing/4529584584", directUrl: "https://payhip.com/b/DQS5l", desc: "Contribution room, live prices, ACB" },
  { name: "TFSA Multi-Brokerage Tracker", tag: "TFSA", price: 9.99, url: "https://www.etsy.com/listing/4541253114", directUrl: "https://payhip.com/b/8CqQU", desc: "Up to 8 brokerages in one sheet — the only one of its kind", badge: "NEW" },
  { name: "RESP Tracker", tag: "RESP", price: 14.99, url: "https://www.etsy.com/listing/4530779418", directUrl: "https://payhip.com/b/w8PXD", desc: "CESG grants, up to 4 beneficiaries" },
  { name: "FHSA Tracker", tag: "FHSA", price: 14.99, url: "https://www.etsy.com/listing/4534938230", directUrl: "https://payhip.com/b/dEXy3", desc: "First Home Savings, Line 20805 tax dashboard" },
  { name: "Margin Account Tracker", tag: "Margin", price: 14.99, url: "https://www.etsy.com/listing/4534229751", directUrl: "https://payhip.com/b/yKoBQ", desc: "ACB, capital gains tax dashboard" },
  // ⚠️ Lino: double-check this one — you sent "fSgIz" (capital I), earlier test-purchase record shows "fSglz" (lowercase l). Same-looking chars, please verify against your Payhip dashboard before publishing.
  { name: "TFSA + RRSP Tracker", tag: "Combo", price: 19.99, url: "https://www.etsy.com/listing/4522093988", directUrl: "https://payhip.com/b/fSgIz", desc: "Our original — both registered accounts, one sheet" },
  { name: "RRSP + Spousal RRSP Tracker", tag: "Combo", price: 19.99, url: "https://www.etsy.com/listing/4535354991", directUrl: "https://payhip.com/b/mdRzx", desc: "Income splitting, attribution rules, Line 208" },
  { name: "TFSA + Margin Linked Tracker", tag: "Combo", price: 24.99, url: "https://www.etsy.com/listing/4534821592", directUrl: "https://payhip.com/b/dOqcI", desc: "Linked accounts with collateral tax dashboard" },
  { name: "TFSA + RRSP + Margin Tracker", tag: "Combo", price: 27.99, url: "https://www.etsy.com/listing/4523804765", directUrl: "https://payhip.com/b/29CVO", desc: "Registered + taxable in one place" },
  { name: "TFSA + RRSP + RESP Tracker", tag: "Combo", price: 27.99, url: "https://www.etsy.com/listing/4526534020", directUrl: "https://payhip.com/b/DrfbA", desc: "Family bundle with CESG maximizer" },
  { name: "TFSA + RRSP + RESP + Margin", tag: "Combo", price: 34.99, url: "https://www.etsy.com/listing/4528655460", directUrl: "https://payhip.com/b/xNGr1", desc: "Four accounts — ACB, CESG, capital gains" },
  { name: "Ultimate Tracker — All 5 Accounts", tag: "Flagship", price: 44.99, url: "https://www.etsy.com/listing/4536628550", directUrl: "https://payhip.com/b/wkqoH", desc: "TFSA + RRSP + RESP + FHSA + Margin. Everything, one sheet.", badge: "FLAGSHIP" },
];

// ─── Resources: add a new object to the TOP of this list to publish a post.
// type: "video" (YouTube embed) or "article" (text post)
// For videos: youtubeId is the part after v= in the URL (e.g. dQw4w9WgXcQ)
export const RESOURCES = [
  // ─── DRAFT QUEUE — write once, it auto-publishes on its date ────
  // Articles appear on the site automatically once their `date` arrives — no
  // need to flip anything. Just write the article and set the date you want
  // it to go live. Only add `live: false` if the content genuinely isn't
  // ready yet (e.g. a video with no youtubeId) — that will hide it even
  // after its date passes, until you remove the flag.
  {
    type: "article",
    title: "How to Start Investing in Canada With Just $100",
    slug: "start-investing-with-100",
    image: "/resources/start-investing-100.jpg",
    date: "2026-08-13",
    live: true,
    summary: "You don't need thousands saved up to start. Here's exactly what $100 can actually buy you in the Canadian investing system — and why starting now beats waiting for more.",
    body: [
      "$100 feels small next to headlines about retiring with a million dollars, so a lot of people wait until they have \"real money\" before they start. That's backwards. The account and the habit matter more at this stage than the amount — and $100 is enough to open both.",
      "## Pick the account before the investment",
      "For most first-time investors in Canada, a TFSA is the natural place to start. There's no minimum balance to open one, growth and withdrawals are completely tax-free, and unlike an RRSP there's no requirement to have earned income first. Open the account, transfer your $100, and you already have contribution room sitting there — Canadians who've been eligible since 2009 and never contributed have well over $100,000 in cumulative TFSA room waiting to be used.",
      "## What $100 can actually buy",
      "A single share of some companies costs more than $100 on its own, which used to be the real barrier to starting small. That's changed — most major Canadian brokerages now support fractional shares and let you buy partial units of broad, diversified ETFs with no minimum purchase size. That means $100 can buy you a slice of hundreds of companies at once through a single all-in-one asset-allocation ETF, instead of betting everything on one stock you picked because you recognized the name.",
      "## The real risk at $100 isn't picking wrong",
      "With a small amount, the biggest risk isn't choosing the \"wrong\" ETF — reasonable diversified options tend to perform similarly to each other over time. The real risk is treating $100 as a one-time experiment instead of the first deposit in a recurring habit. Someone who invests $100 once and stops has a very different outcome, decades later, than someone who invests $100 a month, every month, without exception.",
      "## What waiting actually costs you",
      "Assume a 7% average annual return, a reasonable long-run figure for a diversified equity portfolio, though real returns vary year to year and are never guaranteed. Investing $100 a month for 30 years grows to roughly $122,000. Wait five years to \"get more settled\" and then invest for the remaining 25 years, and that same $100 a month grows to roughly $81,000 — a gap of about $41,000. You only skipped $6,000 worth of contributions by waiting, but you lost seven times that in growth, because the money you don't invest in your first few years is the money that would have compounded the longest.",
      "## Track it from day one",
      "Opening the account is step one. Knowing your contribution room, what you actually hold, and how it's growing is step two — and that's where most beginners lose track once they're contributing regularly across a few different holdings. Our TFSA Tracker is built to handle exactly that from your very first $100 deposit, so the habit stays easy to keep up with as it grows.",
    ],
  },
  {
    type: "article",
    title: "FHSA: The Complete 2026 Guide to Canada's First Home Savings Account",
    slug: "fhsa-guide",
    image: "/resources/fhsa-guide.jpg",
    date: "2026-08-08",
    live: true,
    summary: "The one account that's deductible like an RRSP and tax-free like a TFSA — and the carry-forward rule that catches people off guard.",
    body: [
      "The FHSA lets first-time buyers contribute up to $8,000 a year, deduct it from taxable income like an RRSP, and withdraw it completely tax-free for a qualifying home purchase like a TFSA. No other Canadian account combines both benefits.",
      "## The numbers for 2026",
      "The annual limit is $8,000, unchanged since the account launched in 2023 — this figure isn't indexed to inflation, so it stays fixed year to year. The lifetime maximum is $40,000, meaning five years of full contributions gets you there.",
      "## The carry-forward cap most people miss",
      "Unused room does carry forward — but only up to $8,000 worth. Contribute $3,000 in your first year, and next year's limit becomes $13,000 ($8,000 new plus $5,000 carried forward), not the full $8,000 plus $5,000 plus another $8,000. The carry-forward caps out at one extra year's worth, so skipping multiple years doesn't stack indefinitely.",
      "## The 15-year and age-71 clock",
      "An FHSA has to be closed within 15 years of opening it, or by the year you turn 71, whichever comes first. If you haven't used the funds for a qualifying home purchase by then, the balance transfers to an RRSP or RRIF tax-free, or gets withdrawn as taxable income.",
      "## Room doesn't start until you open the account",
      "Unlike a TFSA, FHSA room doesn't accumulate in the background before you act — it only starts building the year you actually open the account, even if you were eligible years earlier. Someone who waits five years after becoming eligible to open an FHSA has zero carry-forward waiting for them; the clock simply hadn't started. Opening the account with even a small first contribution locks in that year's room and starts the carry-forward accruing, which is worth doing early even if you're not ready to fund it heavily yet.",
      "## Stacking it with the Home Buyers' Plan",
      "The FHSA and the RRSP's Home Buyers' Plan aren't mutually exclusive — a first-time buyer can use both toward the same home purchase. That pairs the FHSA's up-to-$40,000 tax-free withdrawal with the HBP's up-to-$60,000 RRSP withdrawal, putting up to $100,000 of registered-account money toward a down payment without touching a taxable account, provided both sets of rules are met.",
      "Our FHSA tracker handles both the annual and lifetime room calculations automatically, including the capped carry-forward — so you always know exactly how much you can still contribute this year.",
    ],
  },
  {
    type: "article",
    title: "TFSA vs. RRSP: Which Should You Prioritize First?",
    slug: "tfsa-vs-rrsp",
    image: "/resources/tfsa-vs-rrsp.jpg",
    date: "2026-08-13",
    summary: "There's no universal right answer — but there is a right question to ask yourself, and it comes down to more than just your current paycheque.",
    body: [
      "This is the most common Canadian investing question, and most answers online oversimplify it into \"TFSA if you're young, RRSP if you're older.\" The real deciding factor isn't your age — it's your current marginal tax rate versus your expected tax rate when you eventually withdraw the money, plus a few government-benefit side effects that most people never factor in.",
      "## The core tradeoff",
      "RRSP contributions are deducted from this year's taxable income, so they're most valuable when your tax rate is high right now. TFSA contributions get no upfront deduction, but every dollar of growth and every withdrawal is completely tax-free, forever — which matters most if you expect to be in a similar or higher tax bracket later, or if you value never owing tax on the money again.",
      "## What your marginal rate actually looks like in 2026",
      "The federal brackets for 2026 are 14% up to $58,523, 20.5% from $58,524 to $117,045, 26% from $117,046 to $181,440, 29% from $181,441 to $258,482, and 33% above that. Provincial tax stacks on top of these federal rates and varies by province, so your true combined marginal rate is higher than the federal number alone — often somewhere in the 30-40% range for middle-income earners, higher still at the top. A $5,000 RRSP contribution made while sitting in the 20.5% federal bracket saves you roughly $1,000 in federal tax alone the year you contribute, before provincial savings are even counted.",
      "## Why your retirement tax rate matters more than people think",
      "The deduction you get today is only half the equation. Every dollar you eventually withdraw from an RRSP (or RRIF, which it converts to) gets taxed as regular income in the year you take it out. If your income in retirement ends up lower than it is now, you effectively deducted at a high rate and will pay tax at a lower one — a genuine win. But high earners who contribute heavily for decades sometimes build RRIF balances large enough that mandatory minimum withdrawals after age 71 push their retirement income back into a similar bracket to where they started, shrinking the advantage.",
      "## The clawback trap most people don't see coming",
      "This is the part most comparisons skip entirely. Old Age Security has a recovery tax — commonly called the OAS clawback — that starts reducing your OAS payments once your net income crosses a threshold: $95,323 for the 2026 income year. Above that line, you lose 15 cents of OAS for every extra dollar of net income, until OAS is fully clawed back at $152,062 (ages 65-74). RRSP and RRIF withdrawals count as net income and can push a retiree over that threshold. Lower-income seniors relying on the Guaranteed Income Supplement face a similar problem — GIS is income-tested, and RRIF withdrawals reduce it. TFSA withdrawals count as neither. They never touch your net income, never trigger the OAS clawback, and never reduce GIS — which is a real advantage for anyone who expects to rely on government retirement benefits.",
      "## If your employer offers RRSP matching, that usually comes first",
      "An employer RRSP match is an immediate, guaranteed return that has nothing to do with your tax bracket — turning down free matching dollars to prioritize a TFSA instead almost never makes mathematical sense. Contribute at least enough to capture the full match before weighing TFSA versus additional, unmatched RRSP room.",
      "## A simple rule of thumb",
      "If you're early in your career and in a lower tax bracket, TFSA contributions often make more sense — you're not sacrificing much of a deduction now, and decades of tax-free growth compounds significantly, with none of the future clawback exposure. If you're in your peak earning years and in a high bracket, the RRSP deduction becomes more valuable, especially if you expect a meaningfully lower income in retirement.",
      "## You don't actually have to choose",
      "Contribution room in one account doesn't reduce room in the other — they're entirely independent. Many Canadians end up using both simultaneously: RRSP for the deduction and employer matching during high-income years, TFSA for flexible, tax-free growth that stays invisible to both the CRA and any income-tested benefit calculation.",
      "If you're running both accounts, our TFSA + RRSP combo tracker keeps contribution room, deduction limits, and growth for both in one dashboard — so you can see the full picture instead of switching between two spreadsheets.",
    ],
  },
  {
    type: "article",
    title: "RESP & CESG: How the 20% Government Match Actually Works",
    slug: "resp-cesg-explained",
    image: "/resources/resp-cesg.jpg",
    date: "2026-08-20",
    summary: "Free money from the government, with a lifetime cap most parents don't realize they're tracking against.",
    body: [
      "The Canada Education Savings Grant matches 20% of what you contribute to a child's RESP, up to $500 per year — meaning a $2,500 annual contribution gets the full match. Miss a year, and that unused grant room carries forward, up to a point.",
      "## The lifetime cap that matters more than the annual one",
      "The $500-per-year figure gets most of the attention, but the number that actually matters long-term is the $7,200 lifetime CESG maximum per child. Once you've received $7,200 in grants total, no further government matching happens — regardless of how much more you contribute.",
      "## Catch-up contributions",
      "If you didn't contribute in previous years, you can catch up — but the grant only matches up to $1,000 per year in catch-up room (on top of the current year's $500), so you can't simply dump in years of missed contributions and collect years of missed grants all at once.",
      "## The RESP contribution limit itself",
      "Separate from the grant, the RESP account itself has a $50,000 lifetime contribution limit per beneficiary — contributions beyond that aren't illegal, just no longer grant-eligible or tax-sheltered in the same way. Go over it and the CRA applies a 1% per month penalty on the excess until it's withdrawn.",
      "## Extra grants lower-income families shouldn't leave unclaimed",
      "Beyond the base 20% CESG, families under certain income thresholds qualify for the Additional CESG — an extra 10% or 20% on top of the standard match, on the first $500 contributed each year. On top of that, the Canada Learning Bond can add up to $2,000 to an eligible child's RESP with no contribution required at all — the government deposits it simply because the child qualifies, based on Canada Child Benefit eligibility. Both these programs are the ones most commonly missed, precisely because they don't require writing a cheque to trigger them.",
      "## What happens if the RESP is never used",
      "An RESP has a maximum life of 35 years from the day it's opened, after which it has to be closed. If the beneficiary never pursues education that qualifies, your own contributions come back to you tax-free, but any CESG, Additional CESG, and Canada Learning Bond money in the account has to be repaid to the government — it was never yours to keep unconditionally. Growth on the investments can sometimes be transferred to your RRSP (if you have room) or withdrawn as taxable income, subject to additional tax.",
      "Our RESP tracker runs the CESG math automatically against both the annual and lifetime caps, so you know exactly how much unclaimed grant room is left before your child ages out of eligibility.",
    ],
  },
  // ─── LIVE ARTICLES ───────────────────────────────────────────────
  {
    type: "article",
    title: "TFSA Contribution Room in 2026: The Complete Guide",
    slug: "tfsa-contribution-room-2026",
    image: "/resources/tfsa-room.jpg",
    date: "2026-07-30",
    summary: "The 2026 TFSA limit, how cumulative room actually adds up, and the withdrawal rule that trips up even experienced investors.",
    body: [
      "The TFSA annual dollar limit for 2026 is $7,000 — the third year in a row it's held at that number after a run of increases. If you've been eligible since the TFSA started in 2009 and have never contributed, your cumulative room now sits at $109,000.",
      "## How contribution room actually adds up",
      "Room isn't just this year's $7,000. It's the sum of every annual limit since the year you turned 18 (or since 2009, whichever is later), plus any amount you've withdrawn in a previous calendar year, minus whatever you've already contributed. Unused room never expires — it carries forward indefinitely, which is exactly why long-time TFSA holders can have six-figure room even if they've barely contributed.",
      "## The withdrawal rule that catches people off guard",
      "Withdrawing money from a TFSA doesn't shrink your lifetime room — but it also doesn't restore it immediately. If you pull out $5,000 this year, that $5,000 gets added back to your room on January 1 of next year, not the same day you withdraw it. Contribute that same $5,000 again before the calendar flips, and you've over-contributed.",
      "## What the over-contribution penalty actually costs",
      "The CRA doesn't give any grace on this one — even $1 over your room triggers it. Under the Income Tax Act, excess TFSA contributions are taxed at 1% of the highest excess amount for every month the overage sits in the account, and that clock keeps running until you either withdraw the excess or new contribution room opens up. Go over by $6,000 in March and not notice until August, and you're looking at six months of 1% charges on that $6,000 — roughly $360, plus whatever else compounds while you sort it out. If it genuinely happened by honest mistake, you can request a cancellation or waiver of the penalty from the CRA, but that's discretionary, not guaranteed.",
      "## The one thing a TFSA doesn't shield you from",
      "TFSAs are tax-free under Canadian law, but the US doesn't recognize them as a retirement account the way it recognizes RRSPs under the Canada-US tax treaty. That means US-listed stocks and ETFs held inside a TFSA still have a 15% US withholding tax deducted from their dividends before the cash ever reaches you — a quiet cost that catches people who assume \"tax-free account\" means tax-free on everything inside it, regardless of what it holds.",
      "## Why this is hard to track by hand",
      "The CRA's own portal often lags behind your actual contributions, especially early in the year — which means the number it shows you isn't always the number you can safely rely on. Between multiple brokerages, withdrawals from prior years, and this year's fresh room, keeping an accurate running total takes more than memory.",
      "That's the exact problem our TFSA trackers solve — automatic room calculation that accounts for withdrawals, carry-forward, and multiple institutions, so you're never guessing.",
    ],
  },
  {
    type: "article",
    title: "RRSP Deduction Limit vs. Contribution Room: What's the Difference?",
    slug: "rrsp-deduction-limit-vs-contribution-room",
    image: "/resources/rrsp-deduction.jpg",
    date: "2026-07-28",
    summary: "They sound like the same number. They're usually not — and mixing them up is one of the most common RRSP mistakes.",
    body: [
      "Your RRSP contribution room for 2026 is 18% of your 2025 earned income, up to a maximum of $33,810. That's the ceiling the CRA sets on how much new room you earn this year. But the number on your Notice of Assessment — your deduction limit — isn't the same thing, and the difference matters at tax time.",
      "## Contribution room vs. deduction limit",
      "Contribution room is the running total of everything you're allowed to have contributed, ever — this year's new room plus any unused room carried forward from every prior year. Your deduction limit, shown on your CRA Notice of Assessment, is that same figure adjusted for a few extra factors: a pension adjustment if you belong to an employer pension plan, and any contributions you've already made that haven't been deducted yet. For most people without a workplace pension, the two numbers are close. For anyone with a pension plan, they can diverge meaningfully.",
      "## The first-60-days rule",
      "RRSP contributions made in the first 60 days of a calendar year can be applied to either that year or the previous year's tax return — your choice. This is the single most useful piece of RRSP timing flexibility available, and it's also the rule most people forget exists until their accountant asks about it in March.",
      "## What earned income doesn't include",
      "Investment income, capital gains, and pension income don't count toward earned income for RRSP room purposes — only employment, self-employment, and a few other specific categories do. If most of your income comes from investments, your RRSP room may grow slower than you'd expect.",
      "## The $2,000 cushion that isn't really a bonus",
      "The CRA allows a lifetime $2,000 buffer above your deduction limit with no penalty — but it's easy to misread as \"$2,000 of extra room.\" It isn't. Contributions inside that cushion still can't be deducted from your taxable income beyond your actual limit; the buffer just protects you from the 1% monthly over-contribution tax if you accidentally go slightly over. Exceed your limit plus that $2,000 cushion, and the CRA applies a 1% per month penalty on the excess, calculated at the end of each month it remains — and you're required to file a T1-OVP return within 90 days of year-end to report it, or a late-filing penalty stacks on top.",
      "## Two ways to use RRSP room beyond your own retirement",
      "A spousal RRSP lets the higher-income partner contribute using their own deduction limit into an RRSP registered in the lower-income spouse's name — the deduction goes to the contributor, but future withdrawals are taxed to the spouse, which can split retirement income and lower the household's combined tax bill. Separately, the Home Buyers' Plan lets a first-time buyer withdraw up to $60,000 tax-free from their RRSP toward a home purchase, repaid over 15 years starting the second year after the withdrawal — miss a year's minimum repayment and that installment gets added straight to your taxable income instead of quietly rolling forward.",
      "Our RRSP trackers pull your actual deduction limit as an editable field rather than assuming a flat number, so the tracker matches what your Notice of Assessment actually says — not a generic formula.",
    ],
  },
  {
    type: "article",
    title: "How Adjusted Cost Base (ACB) Works for Canadian Investors",
    slug: "how-acb-works",
    image: "/resources/acb-explained.jpg",
    date: "2026-07-26",
    summary: "The number that determines how much tax you actually owe when you sell — and why most spreadsheets get it wrong.",
    body: [
      "Adjusted cost base, or ACB, is what the CRA uses to figure out your capital gain or loss when you sell an investment. Get it wrong, and you either overpay tax or under-report — neither of which you want to explain in an audit.",
      "## The core formula",
      "ACB is your average cost per share across every purchase of that security, not the price of your most recent buy. Every time you buy more shares of something you already hold, your ACB recalculates as a weighted average of the old and new cost. Sell shares, and your ACB per remaining share stays the same — only the total drops proportionally.",
      "## Capital gains stay at the 50% inclusion rate",
      "For 2026, capital gains are still taxed at the 50% inclusion rate — meaning only half of your gain gets added to your taxable income. A proposed increase to two-thirds on gains above $250,000 was cancelled, so the math investors have used for years still applies. Your gain is simply your sale proceeds minus your ACB, minus any transaction costs, with half of that result taxed at your marginal rate.",
      "## Why this gets complicated fast",
      "Dividend reinvestment plans, stock splits, return-of-capital distributions, and buying the same stock across multiple brokerages all adjust your ACB — and most people's mental math (or a basic spreadsheet) doesn't account for all of it. A single missed adjustment years ago compounds into a wrong number today.",
      "## The superficial loss rule that quietly cancels tax-loss selling",
      "Sell a losing stock to claim the capital loss, then buy it back within 30 days — before or after the sale — and the CRA treats it as a superficial loss under section 54 of the Income Tax Act. The loss gets denied for that year entirely. It isn't gone forever, though: it gets added back onto the ACB of the shares you repurchased, deferring the loss until you eventually sell those shares for good, outside the 61-day window around any future purchase.",
      "## US dollar holdings need converting, not just tracking",
      "If you hold US-listed stocks or ETFs, your ACB has to be recorded in Canadian dollars — using the exchange rate on the actual date of each transaction, not today's rate. Buy the same US stock on three different dates at three different exchange rates, and each purchase converts separately before averaging into your ACB. Skip the conversion and use a single rate for everything, and your reported gain or loss is off, sometimes significantly, purely from currency movement having nothing to do with the stock itself.",
      "This is exactly why our Margin and multi-brokerage trackers calculate ACB automatically as you log each transaction, instead of asking you to track a running average by hand.",
    ],
  },
  {
    type: "article",
    title: "Welcome to MapleSheet Resources",
    slug: "welcome",
    image: "/resources/welcome.jpg",
    date: "2026-07-22",
    summary: "Learn first. Track smarter. Make better financial decisions.",
    body: [
      "Welcome to the MapleSheet Resources Hub — a growing library of practical, easy-to-understand resources created for Canadian DIY investors.",
      "At MapleSheet Co., we believe you should understand your money before you track it. A spreadsheet or tracker can organize your investments, but knowing what you're tracking, why it matters, and how the Canadian rules work is what helps you make better decisions.",
      "That's why we're building this resource hub alongside our investment trackers and tools — straightforward guides on Canada's most important investment accounts, tax concepts, and personal-finance strategies, without unnecessary jargon.",
      "## What you'll find here",
      "🍁 TFSA — how contribution room works, how withdrawals affect future room, how over-contributions happen, and how to track your available room across different institutions.",
      "💼 RRSP — contribution room, deduction limits, contribution timing, withdrawals, tax deductions, and the rules that can affect your retirement strategy.",
      "🏠 FHSA — how Canada's First Home Savings Account works, including contribution limits, tax deductions, qualifying withdrawals, and how it fits into a first-home savings strategy.",
      "🎓 RESP — the basics of saving for education, including contributions, government grants like the CESG, investment growth, and the different types of withdrawals.",
      "📊 Non-registered & margin investing — adjusted cost base (ACB), capital gains, dividends, investment income, and the record-keeping that comes with taxable investments.",
      "🧮 Investing & portfolio tracking — how to organize your investments, monitor contributions, track dividends, calculate returns, and keep everything in one place.",
      "## Learn the concept, then track it",
      "Reading about TFSA contribution room is useful. Understanding ACB is useful. Learning how RRSP deductions work is useful. But being able to actually track these things in your own financial life is where the knowledge becomes practical.",
      "That's why many of our educational resources connect directly with the MapleSheet trackers we build — we'll show you not just what something means, but how to organize and track it.",
      "## Step-by-step tracker walkthroughs",
      "We also publish walkthroughs for our MapleSheet products so you can get the most out of your tracker — what each section does, how to enter your information, how the calculations work, and how to interpret the numbers on your dashboard. The goal isn't a complicated spreadsheet that requires you to be a spreadsheet expert — it's a clearer picture of your money.",
      "## New resources every week",
      "This hub will keep growing, with new articles on Canadian investing, registered accounts, taxes, portfolio management, and practical investing concepts every DIY investor should understand. We'll also publish videos and walkthroughs for topics that are easier to follow when you can see them in action — new videos land on our YouTube channel first, then get posted here with supporting notes. Read the articles, watch the videos, or explore the trackers — whichever fits how you learn.",
      "## Built for Canadian DIY investors",
      "You don't need to be a financial expert to become more organized and informed about your money. Whether you're starting with your first $100, building your TFSA, contributing to an RRSP, saving for your first home, investing for your children's education, or managing a larger portfolio, our goal is to make the information easier to understand and easier to apply. Investing doesn't have to start with a large amount — it can start with one contribution, one account, and one better decision at a time.",
      "MapleSheet isn't about telling you what to buy or predicting the market. It's about helping you understand, organize, and track your financial journey so you can make decisions with better information. Explore the guides, learn at your own pace, and use the tools that make sense for your situation.",
      "Knowledge first. Tracking second. Better decisions every step of the way. Welcome to MapleSheet Resources.",
    ],
  },
  // Example video post — Lino: replace youtubeId with a real video and set live: true
  {
    type: "video",
    title: "Tracker walkthrough (video coming soon)",
    date: "2026-07-22",
    summary: "Our first walkthrough video will appear here — how to set up your MapleSheet tracker in under 10 minutes.",
    youtubeId: "",
    live: false,
  },
];

export const FAQS = [
  ["Do I need Excel or Google Sheets?", "Google Sheets — which is free with any Google account. No Excel needed, no software to install. You'll receive a link, click 'Make a copy', and the tracker is yours."],
  ["Is this a subscription?", "No. One-time purchase, yours forever. Free updates to the version you bought, and no recurring fees of any kind."],
  ["How do live prices work?", "Trackers use Google's built-in GOOGLEFINANCE function to pull live stock and ETF quotes automatically — CAD and USD, with automatic currency conversion."],
  ["Will it work on my phone?", "Yes — through the free Google Sheets app. The dashboards are designed on desktop but fully usable on mobile."],
  ["Does it handle Canadian tax rules?", "That's the whole point. TFSA contribution room, RRSP deduction limits, FHSA Line 20805, CESG grant tracking, ACB and capital gains with the 50% inclusion rate — built the CRA way."],
  ["What if I need help?", "Email us. Every buyer gets personal support from Lino directly — no bots, no auto-replies."],
  ["What's your refund policy?", "Because these are instant digital downloads, Etsy's digital-goods policy applies — but if something isn't working, contact us first. We fix problems."],
];
