// ─── MapleSheet Co. — central data & config ─────────────────────
// Lino: this is the ONE file you'll edit most often.

export const CONFIG = {
  shopUrl: "https://maplesheetco.etsy.com",
  calcUrl: "https://claude.ai/public/artifacts/1620ddd7-219c-4052-8557-2a8c6d63e7fb",
  email: "hello@maplesheet.ca",
  xUrl: "https://x.com/MapleSheetCo",
  youtubeUrl: "https://www.youtube.com/@MapleSheetCo", // ← Lino: confirm handle
  affiliateUrl: "https://payhip.com/auth/register/af6a64b512341ea",
  promoCode: "MAPLE25",
  promoText: "25% off everything with code MAPLE25",
  freeToolUrl: "https://claude.ai/public/artifacts/1620ddd7-219c-4052-8557-2a8c6d63e7fb",
  // Web3Forms: create a free access key at https://web3forms.com (enter hello@maplesheet.ca)
  // and paste it below to activate the contact + newsletter forms:
  web3formsKey: "88c72f3b-a279-446a-871b-91d29a308bc5",
  // Google Analytics: create a GA4 property, then paste your Measurement ID
  // (GA4 Admin → Data Streams → Web) here. NOTE: index.html also needs the
  // same ID pasted into its gtag.js snippet — that page loads before React,
  // so it can't read this file. Keep both in sync.
  gaMeasurementId: "G-VE0JSFXE1Q",
};

export const B = {
  black: "#131312",
  black2: "#1B1B1A",
  black3: "#232322",
  white: "#FFFFFF",
  red: "#CC0000",
  redHover: "#DC2626",
  gray: "#5C5C5B",
  grayLight: "#9C9C9A",
  line: "#2E2E2C",
  yellow: "#FCD34D",
};

export const PRODUCTS = [
  { name: "TFSA Tracker", tag: "TFSA", price: 9.99, url: "https://www.etsy.com/listing/4529134188", directUrl: "https://payhip.com/b/rb9SR", desc: "Live prices, ACB, dividends, tax-free growth" },
  { name: "RRSP Tracker", tag: "RRSP", price: 9.99, url: "https://www.etsy.com/listing/4529584584", directUrl: "https://payhip.com/b/DQS5l", desc: "Contribution room, live prices, ACB" },
  { name: "TFSA Multi-Brokerage Tracker", tag: "TFSA", price: 9.99, url: "https://www.etsy.com/listing/4541253114", directUrl: "https://payhip.com/b/8CqQU", desc: "Up to 8 brokerages in one sheet — the only one of its kind", badge: "NEW" },
  { name: "RESP Tracker", tag: "RESP", price: 14.99, url: "https://www.etsy.com/listing/4530779418", directUrl: "https://payhip.com/b/w8PXD", desc: "CESG grants, up to 4 beneficiaries" },
  { name: "FHSA Tracker", tag: "FHSA", price: 14.99, url: "https://www.etsy.com/listing/4534938230", directUrl: "https://payhip.com/b/dEXy3", desc: "First Home Savings, Line 20805 tax dashboard" },
  { name: "Margin Account Tracker", tag: "Margin", price: 14.99, url: "https://www.etsy.com/listing/4534229751", directUrl: "https://payhip.com/b/yKoBQ", desc: "ACB, capital gains tax dashboard" },
  // ⚠️ Lino: double-check this one — you sent "fSgIz" (capital I), earlier test-purchase record shows "fSglz" (lowercase l). Same-looking chars, please verify against your Payhip dashboard before publishing.
  { name: "TFSA + RRSP Tracker", tag: "Combo", price: 19.99, url: "https://www.etsy.com/listing/4522093988", directUrl: "https://payhip.com/b/fSgIz", desc: "Our original — both registered accounts, one sheet" },
  { name: "RRSP + Spousal RRSP Tracker", tag: "Combo", price: 19.99, url: "https://www.etsy.com/listing/4535354991", directUrl: "https://payhip.com/b/mdRzx", desc: "Income splitting, attribution rules, Line 208" },
  { name: "TFSA + Margin Linked Tracker", tag: "Combo", price: 24.99, url: "https://www.etsy.com/listing/4534821592", directUrl: "https://payhip.com/b/dOqcI", desc: "Linked accounts with collateral tax dashboard" },
  { name: "TFSA + RRSP + Margin Tracker", tag: "Combo", price: 27.99, url: "https://www.etsy.com/listing/4523804765", directUrl: "https://payhip.com/b/29CVO", desc: "Registered + taxable in one place" },
  { name: "TFSA + RRSP + RESP Tracker", tag: "Combo", price: 27.99, url: "https://www.etsy.com/listing/4526534020", directUrl: "https://payhip.com/b/DrfbA", desc: "Family bundle with CESG maximizer" },
  { name: "TFSA + RRSP + RESP + Margin", tag: "Combo", price: 34.99, url: "https://www.etsy.com/listing/4528655460", directUrl: "https://payhip.com/b/xNGr1", desc: "Four accounts — ACB, CESG, capital gains" },
  { name: "Ultimate Tracker — All 5 Accounts", tag: "Flagship", price: 44.99, url: "https://www.etsy.com/listing/4536628550", directUrl: "https://payhip.com/b/wkqoH", desc: "TFSA + RRSP + RESP + FHSA + Margin. Everything, one sheet.", badge: "FLAGSHIP" },
];

// ─── Resources: add a new object to the TOP of this list to publish a post.
// type: "video" (YouTube embed) or "article" (text post)
// For videos: youtubeId is the part after v= in the URL (e.g. dQw4w9WgXcQ)
export const RESOURCES = [
  // ─── DRAFT QUEUE — write once, it auto-publishes on its date ────
  // Articles appear on the site automatically once their `date` arrives — no
  // need to flip anything. Just write the article and set the date you want
  // it to go live. Only add `live: false` if the content genuinely isn't
  // ready yet (e.g. a video with no youtubeId) — that will hide it even
  // after its date passes, until you remove the flag.
  {
    type: "article",
    title: "Investing vs. Saving: What's the Difference?",
    slug: "investing-vs-saving",
    image: "/resources/investing-vs-saving.jpg",
    date: "2026-08-17",
    summary: "They're not competing philosophies — they're two different tools, each with its own job. Understanding which one your money needs is the real starting question.",
    body: [
      "Saving and investing both build toward a stronger financial future, but they serve different purposes. Saving is about protecting money and keeping it accessible. Investing is about putting money to work with the potential to grow over time. Neither is automatically better — the right choice depends on what the money is for and when you'll need it.",
      "## What saving is for",
      "Savings accounts, high-interest savings accounts (HISAs), GICs, and short-term cash all share the same goal: preservation and accessibility, not growth. If you'll need $5,000 in a few months for a known expense, putting it somewhere that can lose value doesn't make sense — you don't want to be forced to sell an investment after a market dip simply because the timing of your expense is fixed. Saving fits emergency funds, near-term goals like a vehicle or renovation, and any money you genuinely can't afford to see drop in value.",
      "## What investing is for",
      "Stocks, ETFs, bonds, mutual funds, and real estate can all rise or fall in value — that uncertainty is the trade-off for higher long-term growth potential. $100 invested could become $110 after a 10% gain, or $90 after a 10% loss. That volatility is exactly why investing suits money you won't need soon, not money earmarked for next month's bills.",
      "## Why time matters more than the return rate",
      "The advantage of investing early isn't a guaranteed annual return — markets don't deliver the same number every year. It's that returns generating further returns, compounded over decades, tend to reward the money that's been invested longest. The earlier you start, the more time your money has to compound, which is why starting small today usually beats waiting to start bigger later.",
      "## Don't invest the money you can't afford to lose access to",
      "Investing your entire emergency fund and then facing an unexpected $2,000 repair during a market downturn means selling investments at a bad time to cover it. A healthy strategy keeps both: savings for money you need to protect, investments for money you want to grow — not one at the expense of the other.",
      "## Where TFSA and RRSP actually fit in",
      "A TFSA or RRSP isn't an investment itself — it's a registered account that can hold investments (or just sit as cash). It helps to separate the two ideas: the account is where your money is held (TFSA, RRSP, FHSA, RESP, or a non-registered account), while the investment is what you actually own inside it (stocks, ETFs, bonds, GICs, or cash). Opening a TFSA doesn't automatically mean your money is invested — you still have to choose what goes inside it.",
      "## The same $10,000, two different strategies",
      "Someone who needs $10,000 in six months for a home renovation should prioritize preserving that money and keeping it accessible — a lower-risk option makes more sense than exposing it to short-term market swings. Someone with the same $10,000 who won't touch it for 20 years of retirement saving is in a completely different position, with room to accept more volatility in exchange for long-term growth potential. Same amount, different purpose, different strategy.",
      "## Inflation is the reason cash alone isn't a complete plan",
      "Money that earns very little while prices rise loses purchasing power over time, even if the number in the account never goes down. That's not an argument for investing every dollar — it's the reason a long-term plan usually needs both stability from savings and growth potential from investments.",
      "## Start with the goal, not the ticker",
      "Rather than asking \"what should I buy,\" start with \"what is this money for.\" When you'll need it, whether you can tolerate its value dropping temporarily, what account makes sense, and how much you can contribute consistently — those questions shape a strategy before you pick a single investment.",
      "Short-term money — emergencies, upcoming purchases, near-term goals — belongs in savings. Long-term money — retirement, long-term wealth building — is where investing earns its place. Most people need both running at once, and MapleSheet's trackers are built to keep the picture organized either way: what you're protecting, what you're growing, and how each is actually doing.",
    ],
  },
  {
    type: "article",
    title: "How to Start Investing in Canada With Just $100",
    slug: "start-investing-with-100",
    image: "/resources/start-investing-100.jpg",
    date: "2026-08-13",
    live: true,
    summary: "You don't need thousands saved up to start. Here's exactly what $100 can actually buy you in the Canadian investing system — and why starting now beats waiting for more.",
    body: [
      "$100 feels small next to headlines about retiring with a million dollars, so a lot of people wait until they have \"real money\" before they start. That's backwards. The account and the habit matter more at this stage than the amount — and $100 is enough to open both.",
      "## Pick the account before the investment",
      "For most first-time investors in Canada, a TFSA is the natural place to start. There's no minimum balance to open one, growth and withdrawals are completely tax-free, and unlike an RRSP there's no requirement to have earned income first. Open the account, transfer your $100, and you already have contribution room sitting there — Canadians who've been eligible since 2009 and never contributed have well over $100,000 in cumulative TFSA room waiting to be used.",
      "## What $100 can actually buy",
      "A single share of some companies costs more than $100 on its own, which used to be the real barrier to starting small. That's changed — most major Canadian brokerages now support fractional shares and let you buy partial units of broad, diversified ETFs with no minimum purchase size. That means $100 can buy you a slice of hundreds of companies at once through a single all-in-one asset-allocation ETF, instead of betting everything on one stock you picked because you recognized the name.",
      "## The real risk at $100 isn't picking wrong",
      "With a small amount, the biggest risk isn't choosing the \"wrong\" ETF — reasonable diversified options tend to perform similarly to each other over time. The real risk is treating $100 as a one-time experiment instead of the first deposit in a recurring habit. Someone who invests $100 once and stops has a very different outcome, decades later, than someone who invests $100 a month, every month, without exception.",
      "## What waiting actually costs you",
      "Assume a 7% average annual return, a reasonable long-run figure for a diversified equity portfolio, though real returns vary year to year and are never guaranteed. Investing $100 a month for 30 years grows to roughly $122,000. Wait five years to \"get more settled\" and then invest for the remaining 25 years, and that same $100 a month grows to roughly $81,000 — a gap of about $41,000. You only skipped $6,000 worth of contributions by waiting, but you lost seven times that in growth, because the money you don't invest in your first few years is the money that would have compounded the longest.",
      "## Track it from day one",
      "Opening the account is step one. Knowing your contribution room, what you actually hold, and how it's growing is step two — and that's where most beginners lose track once they're contributing regularly across a few different holdings. Our TFSA Tracker is built to handle exactly that from your very first $100 deposit, so the habit stays easy to keep up with as it grows.",
    ],
  },
  {
    type: "article",
    title: "FHSA: The Complete 2026 Guide to Canada's First Home Savings Account",
    slug: "fhsa-guide",
    image: "/resources/fhsa-guide.jpg",
    date: "2026-08-08",
    live: true,
    summary: "The one account that's deductible like an RRSP and tax-free like a TFSA — and the carry-forward rule that catches people off guard.",
    body: [
      "The FHSA lets first-time buyers contribute up to $8,000 a year, deduct it from taxable income like an RRSP, and withdraw it completely tax-free for a qualifying home purchase like a TFSA. No other Canadian account combines both benefits.",
      "## The numbers for 2026",
      "The annual limit is $8,000, unchanged since the account launched in 2023 — this figure isn't indexed to inflation, so it stays fixed year to year. The lifetime maximum is $40,000, meaning five years of full contributions gets you there.",
      "## The carry-forward cap most people miss",
      "Unused room does carry forward — but only up to $8,000 worth. Contribute $3,000 in your first year, and next year's limit becomes $13,000 ($8,000 new plus $5,000 carried forward), not the full $8,000 plus $5,000 plus another $8,000. The carry-forward caps out at one extra year's worth, so skipping multiple years doesn't stack indefinitely.",
      "## The 15-year and age-71 clock",
      "An FHSA has to be closed within 15 years of opening it, or by the year you turn 71, whichever comes first. If you haven't used the funds for a qualifying home purchase by then, the balance transfers to an RRSP or RRIF tax-free, or gets withdrawn as taxable income.",
      "## Room doesn't start until you open the account",
      "Unlike a TFSA, FHSA room doesn't accumulate in the background before you act — it only starts building the year you actually open the account, even if you were eligible years earlier. Someone who waits five years after becoming eligible to open an FHSA has zero carry-forward waiting for them; the clock simply hadn't started. Opening the account with even a small first contribution locks in that year's room and starts the carry-forward accruing, which is worth doing early even if you're not ready to fund it heavily yet.",
      "## Stacking it with the Home Buyers' Plan",
      "The FHSA and the RRSP's Home Buyers' Plan aren't mutually exclusive — a first-time buyer can use both toward the same home purchase. That pairs the FHSA's up-to-$40,000 tax-free withdrawal with the HBP's up-to-$60,000 RRSP withdrawal, putting up to $100,000 of registered-account money toward a down payment without touching a taxable account, provided both sets of rules are met.",
      "Our [FHSA tracker](/trackers) handles both the annual and lifetime room calculations automatically, including the capped carry-forward — so you always know exactly how much you can still contribute this year.",
    ],
  },
  {
    type: "article",
    title: "TFSA vs. RRSP: Which Should You Prioritize First?",
    slug: "tfsa-vs-rrsp",
    image: "/resources/tfsa-vs-rrsp.jpg",
    date: "2026-08-13",
    summary: "There's no universal right answer — but there is a right question to ask yourself, and it comes down to more than just your current paycheque.",
    body: [
      "This is the most common Canadian investing question, and most answers online oversimplify it into \"TFSA if you're young, RRSP if you're older.\" The real deciding factor isn't your age — it's your current marginal tax rate versus your expected tax rate when you eventually withdraw the money, plus a few government-benefit side effects that most people never factor in.",
      "## The core tradeoff",
      "RRSP contributions are deducted from this year's taxable income, so they're most valuable when your tax rate is high right now. TFSA contributions get no upfront deduction, but every dollar of growth and every withdrawal is completely tax-free, forever — which matters most if you expect to be in a similar or higher tax bracket later, or if you value never owing tax on the money again.",
      "## What your marginal rate actually looks like in 2026",
      "The federal brackets for 2026 are 14% up to $58,523, 20.5% from $58,524 to $117,045, 26% from $117,046 to $181,440, 29% from $181,441 to $258,482, and 33% above that. Provincial tax stacks on top of these federal rates and varies by province, so your true combined marginal rate is higher than the federal number alone — often somewhere in the 30-40% range for middle-income earners, higher still at the top. A $5,000 RRSP contribution made while sitting in the 20.5% federal bracket saves you roughly $1,000 in federal tax alone the year you contribute, before provincial savings are even counted.",
      "## Why your retirement tax rate matters more than people think",
      "The deduction you get today is only half the equation. Every dollar you eventually withdraw from an RRSP (or RRIF, which it converts to) gets taxed as regular income in the year you take it out. If your income in retirement ends up lower than it is now, you effectively deducted at a high rate and will pay tax at a lower one — a genuine win. But high earners who contribute heavily for decades sometimes build RRIF balances large enough that mandatory minimum withdrawals after age 71 push their retirement income back into a similar bracket to where they started, shrinking the advantage.",
      "## The clawback trap most people don't see coming",
      "This is the part most comparisons skip entirely. Old Age Security has a recovery tax — commonly called the OAS clawback — that starts reducing your OAS payments once your net income crosses a threshold: $95,323 for the 2026 income year. Above that line, you lose 15 cents of OAS for every extra dollar of net income, until OAS is fully clawed back at $152,062 (ages 65-74). RRSP and RRIF withdrawals count as net income and can push a retiree over that threshold. Lower-income seniors relying on the Guaranteed Income Supplement face a similar problem — GIS is income-tested, and RRIF withdrawals reduce it. TFSA withdrawals count as neither. They never touch your net income, never trigger the OAS clawback, and never reduce GIS — which is a real advantage for anyone who expects to rely on government retirement benefits.",
      "## If your employer offers RRSP matching, that usually comes first",
      "An employer RRSP match is an immediate, guaranteed return that has nothing to do with your tax bracket — turning down free matching dollars to prioritize a TFSA instead almost never makes mathematical sense. Contribute at least enough to capture the full match before weighing TFSA versus additional, unmatched RRSP room.",
      "## A simple rule of thumb",
      "If you're early in your career and in a lower tax bracket, TFSA contributions often make more sense — you're not sacrificing much of a deduction now, and decades of tax-free growth compounds significantly, with none of the future clawback exposure. If you're in your peak earning years and in a high bracket, the RRSP deduction becomes more valuable, especially if you expect a meaningfully lower income in retirement.",
      "## You don't actually have to choose",
      "Contribution room in one account doesn't reduce room in the other — they're entirely independent. Many Canadians end up using both simultaneously: RRSP for the deduction and employer matching during high-income years, TFSA for flexible, tax-free growth that stays invisible to both the CRA and any income-tested benefit calculation.",
      "If you're running both accounts, our TFSA + RRSP combo tracker keeps contribution room, deduction limits, and growth for both in one dashboard — so you can see the full picture instead of switching between two spreadsheets.",
    ],
  },
  {
    type: "article",
    title: "RESP & CESG: How the 20% Government Match Actually Works",
    slug: "resp-cesg-explained",
    image: "/resources/resp-cesg.jpg",
    date: "2026-08-20",
    summary: "The government can add up to $7,200 to your child's education fund — but only if you understand the annual room, the carry-forward, and the age-16 deadline that catches late starters.",
    body: [
      "An RESP (Registered Education Savings Plan) is the account a parent, grandparent, or other family member opens for a child's post-secondary education. Money inside grows without being taxed while it stays in the plan — but the real advantage is that you're not saving for education alone. The Canada Education Savings Grant (CESG) adds government money on top of what you contribute.",
      "## The 20% match, in plain numbers",
      "The basic CESG is 20% of the first $2,500 you contribute per beneficiary each year — contribute $2,500, and the government adds $500. Contribute less, and the match scales down proportionally ($1,000 contributed gets $200, for example). Contribute more than $2,500 in a year with no unused room carried forward, and the extra doesn't generate additional basic CESG that year.",
      "## The $7,200 lifetime cap",
      "The CESG isn't unlimited. Once a beneficiary has received $7,200 in total CESG (basic plus any additional CESG), no further government matching happens for that child, regardless of future contributions. Think of it as a 20% grant on eligible contributions, capped both annually and over the child's lifetime — not a standing 20% top-up forever.",
      "## Unused room carries forward — and that enables a real catch-up strategy",
      "Contribute less than $2,500 in a given year, and the unused basic CESG room doesn't disappear — it carries forward. If your finances improve later, you can use that banked room to receive more than the standard $500 in a single year: with enough carried-forward room, a $5,000 contribution in one year can generate up to $1,000 in CESG that year, instead of the usual $500 cap. The $7,200 lifetime maximum still applies regardless.",
      "## Additional CESG most people don't know exists",
      "Beyond the basic 20%, lower- and middle-income families can qualify for Additional CESG on the first $500 contributed each year — an extra 20% for lower-income families or 10% for middle-income families, on top of the standard match. That makes the maximum possible CESG in a single year $600 (20% additional) or $550 (10% additional), rather than the $500 most people assume is the ceiling.",
      "## The RESP itself vs. the CESG — two different things",
      "The RESP is the account; your contributions are your own money going in; the CESG is government money added on top when contributions qualify. The account has its own $50,000 lifetime contribution limit per beneficiary (separate from the $7,200 CESG cap), and unlike an RRSP, RESP contributions are never tax-deductible — the tax advantage is the tax-free growth inside the plan, not a deduction going in.",
      "## The age-16 and 17 deadline that trips up late starters",
      "CESG eligibility generally runs until the end of the year a beneficiary turns 17 — but for contributions made when the child is 16 or 17 to qualify at all, one of two conditions must already have been met by December 31 of the year they turned 15: either at least $2,000 was contributed to the RESP and not withdrawn, or at least $100 was contributed in any four earlier years (not necessarily consecutive). Miss both conditions, and contributions made at 16 or 17 generally don't generate any CESG at all, no matter how much you contribute. This is the single biggest reason to open an RESP early rather than waiting until the teenage years.",
      "## What happens if the beneficiary doesn't pursue eligible education",
      "RESPs cover a wide range of qualifying programs — university, college, CEGEP, trade schools, and apprenticeships, not just a traditional four-year degree. If the beneficiary doesn't end up pursuing eligible post-secondary education, your own contributions come back to you tax-free, but the CESG and any Additional CESG generally have to be repaid to the government — that money was never unconditionally yours. Investment growth may sometimes be transferred to your own RRSP if you have room, or withdrawn as taxable income.",
      "Our [RESP tracker](/trackers) runs the CESG math automatically — annual room, carry-forward, the lifetime cap, and how much of the $50,000 contribution limit remains — so you're not manually reconstructing years of contribution history to figure out what's left.",
    ],
  },
  {
    type: "article",
    title: "TFSA vs. RRSP vs. FHSA vs. RESP: Which Account Should You Open First?",
    slug: "tfsa-vs-rrsp-vs-fhsa-vs-resp",
    date: "2026-08-20",
    summary: "Four accounts, four different jobs — here is the real decision framework, not just \"TFSA if you're young,\" for figuring out which deserves your next dollar.",
    body: [
      "Canadians now have four major tax-advantaged accounts to choose from, and most \"which one should I use\" advice collapses into one-liners that don't hold up: TFSA if you're young, RRSP if you're older, FHSA if you're buying a home. The real answer depends on what the money is actually for, and — for the TFSA and RRSP specifically — your current tax bracket versus your expected tax bracket when you eventually withdraw. Here's the account-by-account comparison, and a practical order to think through it in.",
      "## The 2026 numbers, side by side",
      "| Account | Best for | Tax treatment | 2026 annual limit | Lifetime cap | Withdrawal impact |\n|---|---|---|---|---|---|\n| TFSA | Any goal, flexible access | No deduction; growth & withdrawals tax-free | $7,000 | ~$109,000 cumulative if eligible since 2009 | Room restored next Jan 1 |\n| RRSP | Retirement, income-splitting | Deductible now; taxed on withdrawal | 18% of 2025 earned income, up to $33,810 | No fixed lifetime cap — unused room carries forward indefinitely | Withdrawn room generally doesn't return (Home Buyers' Plan is the exception) |\n| FHSA | A first home purchase | Deductible now AND tax-free on a qualifying withdrawal | $8,000 | $40,000 | Qualifying withdrawal is tax-free; non-qualifying is taxable |\n| RESP | A child's education | No deduction; tax-deferred growth plus a 20% government match | No annual contribution cap (CESG match caps at $2,500 contributed per year) | $50,000 contribution limit per beneficiary; $7,200 CESG cap | Non-educational withdrawals may require repaying the CESG |",
      "## What each account is actually built for",
      "The TFSA is the generalist — nothing else matches its flexibility, since there's no restriction on what the money is eventually used for and no tax consequence either way. The RRSP is specifically a bet that your tax rate in retirement will be lower than it is today, which is usually true for people in their peak earning years but isn't guaranteed. The FHSA only makes sense if a first home purchase is realistically on your horizon — it's the one account here with a defined \"win condition\" instead of open-ended flexibility. The RESP only makes sense if you have a child (or another beneficiary) to save for — it's the only one of the four where someone else's money (the government's) is directly added to yours.",
      "## A practical order to consider — not a universal rule",
      "- **Employer RRSP match first, always.** If your employer matches RRSP contributions, that match is an immediate 100% return before any market performance even factors in — nothing else on this list beats free money.\n- **FHSA next, if a first home is realistically within the next 15 years.** The combination of a deduction now and a tax-free withdrawal later has no equivalent anywhere else in the Canadian system, and FHSA room only starts accumulating once you open the account — so opening it early, even with a small first contribution, is worth doing before you're ready to fund it heavily.\n- **RESP next, if you have a child.** The 20% CESG match is the closest thing to guaranteed government money in this list, and it has an age-16/17 eligibility cliff — waiting costs real, unrecoverable grant money, not just growth time.\n- **TFSA for everything else**, including a general investing goal, an emergency-adjacent fund you still want growing, or simply where money goes once the accounts above are being funded reasonably.\n- **RRSP beyond the employer match** becomes more attractive the higher your current marginal tax rate is relative to your expected rate in retirement — which is a genuinely individual calculation, not a rule of thumb based on age alone.",
      "## You don't have to pick just one",
      "These accounts aren't mutually exclusive, and most Canadians end up using several at once rather than picking a single \"winner.\" A TFSA and RRSP running side by side is normal; adding an FHSA while house-hunting or an RESP once there's a child doesn't require abandoning either. The real constraint most people hit isn't which account to choose — it's how much they can contribute across all of them in a given year, which is exactly why keeping actual room and deduction limits visible matters more than picking a single \"correct\" account.",
      "## Where the FHSA and RRSP can double up",
      "A first-time buyer isn't limited to just the FHSA's up-to-$40,000 tax-free withdrawal. The RRSP's Home Buyers' Plan allows an additional up-to-$60,000 withdrawal toward the same purchase, repaid over 15 years. Used together, that's up to $100,000 of registered-account money available for a down payment, without touching a taxable account — provided both accounts' individual rules are met. See our [FHSA guide](/resources/fhsa-guide) and [RRSP guide](/resources/rrsp-deduction-limit-vs-contribution-room) for the full rules on each.",
      "For the details specific to each account — contribution room math, the rules that trip people up, and what happens if you get it wrong — see our full guides: [TFSA](/resources/tfsa-contribution-room-2026), [RRSP](/resources/rrsp-deduction-limit-vs-contribution-room), [FHSA](/resources/fhsa-guide), and [RESP & CESG](/resources/resp-cesg-explained). And whichever combination you end up using, our [trackers](/trackers) handle the room, deduction limit, and CESG math for all four automatically, so the numbers stay right even when you're juggling more than one account.",
    ],
  },
  {
    type: "article",
    title: "What Should a Beginner Investor Track?",
    slug: "what-should-a-beginner-investor-track",
    image: "/resources/what-should-a-beginner-investor-track.jpg",
    date: "2026-08-24",
    summary: "Your account balance is one number pretending to explain everything. Here's what separating it into pieces actually tells you about how your investing is going.",
    body: [
      "A lot of new investors check exactly one number after they start: today's account balance. But that single figure blends together everything that happened — what you deposited, what the market did, and any dividends you received — into one lump sum that doesn't actually tell you whether your investing is going well. Separating that number into its parts is what turns \"my portfolio went up\" into an actual understanding of your own progress.",
      "## Contributions, separate from growth",
      "The first thing worth tracking on its own is how much you've personally put in, apart from how the market has performed. If you've contributed $3,000 over the past year and your account now shows $3,400, that $400 difference is investment growth — not more money you added. Mixing the two together makes it easy to feel like a better investor than the market has actually made you during a good stretch, or a worse one during a downturn that has nothing to do with your decisions.",
      "## What you actually own",
      "A balance also doesn't say anything about what's inside it. Which ETFs or stocks you hold, how many units of each, and what you paid for them at different points in time all matter once you're contributing regularly — a single monthly purchase becomes several purchases at several prices within a year, and remembering that by memory gets harder the longer you invest.",
      "## Average cost and ACB",
      "Your average cost per share tells you roughly where your break-even point sits. For taxable, non-registered accounts, the more precise version of this — adjusted cost base, or ACB — is what determines your actual capital gain or loss when you eventually sell, and it recalculates every time you buy more of the same holding. A missed adjustment years ago can throw off a number you only need to get right once, at tax time.",
      "## Dividend income",
      "If any of your holdings pay dividends, that income is worth tracking separately from your portfolio's overall growth. It's real cash your investments are generating, distinct from a stock or ETF simply rising in price — and depending on the account it's held in, it may also be taxed differently.",
      "## Contribution room",
      "For registered accounts — TFSA, RRSP, FHSA — how much room you have left depends on your personal contribution and withdrawal history, not just the published annual limit. Contributing past your actual room, even by accident, can trigger a monthly penalty from the CRA. Knowing your running total before you contribute is the only way to avoid finding out after the fact.",
      "## Account type, once you have more than one",
      "Once you're investing through more than one account — a TFSA and an RRSP, or accounts across more than one brokerage — tracking which holdings sit in which account matters, because the tax treatment, contribution rules, and withdrawal consequences are different for each one. A single combined balance hides all of that.",
      "None of this requires a finance background — it just requires separating a few numbers that a basic account balance blends together. That's the gap our trackers are built to close: contributions, holdings, average cost, ACB, dividends, and contribution room, all organized in one place from your very first deposit, so you're working from an actual picture of your investing instead of a single number that changes for reasons you can't see.",
    ],
  },
  {
    type: "article",
    title: "Start Small, Grow Big: How Compound Growth Can Build Your Investment Future",
    slug: "compound-growth-start-small-grow-big",
    image: "/resources/compound-growth.jpg",
    date: "2026-08-31",
    summary: "Why you don't need thousands of dollars to start investing — and why starting early can matter more than starting big.",
    body: [
      "One of the biggest misconceptions about investing is that you need a lot of money before you can get started. You don't. You don't need $10,000. You don't need $50,000. And you don't need to wait until you feel financially \"ready\" to begin learning about investing.",
      "For many Canadians, the more important question isn't \"How much money do I need to start?\" It's \"How much can I start with today—and continue investing over time?\" That's where compound growth becomes important.",
      "A small investment may not look impressive today. But when you combine regular contributions with time and potential investment growth, those small steps can become the foundation of a much larger portfolio.",
      "## What Is Compound Growth?",
      "Compound growth is the idea that your investment can generate returns, and those returns can then contribute to future growth. Think of it like a snowball. At first, the snowball is small. As it rolls, it collects more snow. As it becomes larger, it has the potential to collect even more.",
      "Investing can work in a similar way. You start with your initial contribution. Then you add more money. Your investments may generate returns. Those returns remain invested. Over time, your portfolio has the potential to grow from both your **contributions and investment growth**.",
      "Of course, investment returns aren't guaranteed. Markets can rise and fall, and you can lose money. But the concept of compounding is one of the reasons **time can be such an important part of investing.**",
      "## Starting Small Doesn't Mean Thinking Small",
      "Let's say you have only $100 available to invest. You might look at your account and think: \"What's the point? It's only $100.\" But that $100 isn't the entire story. What if you add another $100 next month? Then another. And another. Suddenly, you've developed something more valuable than a single $100 investment: **a habit.**",
      "For example: $100 → $200 → $300 → $400 → $500. The portfolio is growing because you're continuing to contribute. Then, if your investments generate returns, those returns can add another layer of growth. That's the basic idea behind: **contributions + time + potential growth.**",
      "## The Power of Consistent Contributions",
      "Let's use a simple example. Suppose you invest $100 every month. Over one year, you would contribute $1,200. After five years: $6,000. After ten years: $12,000. After twenty years: $24,000. After thirty years: $36,000. That's the money you personally contributed. But what happens if those investments grow over time? That's where compounding can make a significant difference.",
      "## What Could $100 a Month Become?",
      "Let's use a hypothetical example. Suppose you invest $100 every month for 30 years and your investments earn an average annual return of 7%, compounded monthly. You would contribute $36,000. Over the 30 years, the hypothetical portfolio could grow to approximately $122,000. That means approximately: $36,000 = your contributions, ~$86,000 = hypothetical investment growth.",
      "This is only an illustration. A 7% annual return isn't guaranteed. Real investment returns fluctuate from year to year, and fees, taxes, inflation and market conditions can affect actual results. The purpose of the example is to demonstrate the potential effect of **time and compounding.**",
      "## What If You Start With More?",
      "Now imagine increasing your monthly contribution.",
      "| Monthly Contribution | 30-Year Contributions | Hypothetical Value at 7% |\n|---|---|---|\n| $50 | $18,000 | ~$61,000 |\n| $100 | $36,000 | ~$122,000 |\n| $250 | $90,000 | ~$305,000 |\n| $500 | $180,000 | ~$610,000 |\n| $1,000 | $360,000 | ~$1.22 million |",
      "*Illustration assumes monthly contributions and a constant 7% annual return. Actual investment results will vary.*",
      "The point isn't that you need to invest $1,000 a month. The point is that your contribution amount and the amount of time your money remains invested can both have a major impact on the potential outcome.",
      "## Time Can Be Your Biggest Advantage",
      "Consider two investors. **Investor A** starts investing at age 25 with $100 per month. **Investor B** waits until age 40 and invests $300 per month. Investor B is investing three times as much every month. But Investor A has something Investor B can't buy: **fifteen additional years.**",
      "This is why starting early can be so powerful. You cannot go back and invest the money you didn't invest five or ten years ago. But you can decide what you do with the money you have **today**.",
      "## Don't Wait Until You Have \"Enough\"",
      "This is one of the biggest mistakes beginners can make. They tell themselves: \"I'll start investing when I make more money.\" Then they get a raise. And say: \"I'll start when I pay off a few more things.\" Then another expense appears. There is always another reason to wait.",
      "Of course, you should take care of essential expenses and your overall financial stability first. But if you have money available for long-term investing, you don't necessarily need to wait until you have thousands of dollars. **Starting with $50 or $100 can be a perfectly reasonable way to begin learning.** The amount can grow later.",
      "## Your First $100 Is More Than $100",
      "Your first $100 investment may not make a dramatic difference to your net worth. But it can change your behavior. It teaches you how to: open and use an investment account, place an investment order, understand what you own, track your contributions, watch market movements, understand gains and losses, learn about dividends, understand your account type, and build an investing routine.",
      "That's why your first $100 can be important. **You're not just investing money. You're investing in your financial education.**",
      "## Consistency Can Matter More Than Perfection",
      "Many new investors spend a lot of time trying to figure out the perfect investment. But there's another question that's just as important: can I consistently invest over the next 10, 20 or 30 years? A perfect strategy that you abandon after six months isn't very useful. A simple strategy that you understand and can maintain may be much easier to stick with.",
      "That's one reason regular contributions can be powerful. For example: every payday → $50 invested. If you're paid twice a month: $50 × 2 = $100/month. Over time, that routine can become part of your financial life.",
      "## What Happens When Your Income Increases?",
      "Starting small doesn't mean you have to stay small. Imagine you begin with $100/month. A few years later, your income increases. You increase your contribution to $150/month. Later: $200/month. Then: $300/month. Your investment contribution grows alongside your financial capacity. This can be easier than trying to start with a large monthly contribution immediately.",
      "## Compound Growth Isn't the Same as Guaranteed Growth",
      "This distinction is extremely important. Compound growth is a mathematical concept. The stock market doesn't guarantee a particular return. Your investments could increase in value, decrease in value, remain relatively flat, or experience significant volatility. A hypothetical 7% return should never be interpreted as a promise. You should choose investments based on your goals, time horizon and ability to tolerate risk.",
      "## Where Do You Actually Start Investing?",
      "Once you've decided to start investing, you'll need an investment account and a brokerage or investment platform. As a Canadian DIY investor, I personally use both [Wealthsimple](https://wealthsimple.com/invite/R7ENSA) and [Questrade](https://www.questrade.com) (code: 786314335499127). They're two examples of Canadian platforms that investors can research when deciding where to invest.",
      "[Wealthsimple](https://wealthsimple.com/invite/R7ENSA) — You can explore Wealthsimple if you're looking for a Canadian investing platform.",
      "[Questrade](https://www.questrade.com) (code: 786314335499127) — You can also explore Questrade as another option for self-directed investors.",
      "Neither platform is automatically right for everyone. When choosing a brokerage, consider things such as: account types, investment choices, trading costs, foreign-exchange costs, features, ease of use, customer support, and your own investment strategy.",
      "### Referral Disclosure",
      "Some links in this article may be referral links. If you open an account through a MapleSheet referral link, MapleSheet Co. may receive a referral benefit at no additional cost to you. We mention [Wealthsimple](https://wealthsimple.com/invite/R7ENSA) and [Questrade](https://www.questrade.com) (code: 786314335499127) because they are services I personally use and because they may be useful for Canadian investors to research. This does not mean either platform is suitable for everyone.",
      "## What Account Should You Use?",
      "The brokerage is only part of the equation. You also need to understand the type of investment account you're using. Depending on your circumstances and goals, you may consider accounts such as: TFSA, RRSP, FHSA, RESP, or a non-registered account. Each has different rules and purposes.",
      "For example, a TFSA can hold investments and generally allows investment income and capital gains to grow tax-free. But your personal TFSA contribution room depends on your individual circumstances. That's why understanding and tracking your contribution room is important.",
      "## Why Tracking Matters From Day One",
      "You might think: \"My portfolio is only $100. Why would I need a tracker?\" Because someday it might not be $100. It might be $1,000. Then $10,000. Then $50,000. Then potentially much more.",
      "As your portfolio grows, so does the amount of information you need to keep track of. You may eventually have: multiple accounts, multiple brokerages, multiple investments, dividend income, different purchase prices, multiple transactions, withdrawals, contributions, ACB calculations, and capital gains. That's why building the tracking habit early can be useful.",
      "## Your Brokerage Shows You Your Account",
      "Your brokerage is where you buy and sell your investments. But as your portfolio becomes more complicated, you may want a broader view. That's where MapleSheet comes in. MapleSheet is designed to help Canadian DIY investors organize and understand their investment information.",
      "You can track things such as: contributions, holdings, dividends, purchase prices, average cost, ACB, portfolio performance, investment income, account types, and overall portfolio progress. Instead of simply asking \"How much is my portfolio worth?\" you can start asking: \"How much have I contributed?\" \"How much has my portfolio grown?\" \"How much dividend income am I receiving?\" \"What's my average cost?\" \"How is each account performing?\" That's the difference between simply owning investments and understanding your investments.",
      "## Start With What You Can Afford",
      "There's no universal \"correct\" amount to invest every month. For one person, it might be $25. For another: $100. For someone else: $500. The right amount is the amount that fits your financial situation and doesn't interfere with essential expenses or financial obligations. Don't invest money you know you'll need for your immediate expenses. And don't feel pressured to match someone else's investment amount. **Your financial journey is your own.**",
      "## Small Steps Can Become a Big Journey",
      "Imagine looking back 20 years from now. Would you rather say \"I wish I had started\" or \"I'm glad I started with what I could afford\"? You can't control what the market will do tomorrow. You can't guarantee what your investments will be worth in 20 years. But you can control: when you start, how much you contribute, how consistently you invest, how much you learn, and how carefully you track your progress.",
      "## The MapleSheet Approach",
      "At MapleSheet, we believe investing doesn't have to begin with a huge portfolio. It can begin with a simple decision: start. Then: invest, track, learn, repeat. As your income and knowledge grow, your contributions can grow too. And while compound growth isn't guaranteed, giving your investments more time can give them more opportunity to potentially grow.",
      "## Your First Investment Doesn't Have to Be Big",
      "Maybe your first investment is $25. Maybe it's $50. Maybe it's $100. That's okay. Don't underestimate the importance of getting started. Because the most valuable thing about your first investment may not be the amount of money you put in. **It may be the habit you build from it.**",
      "## Final Takeaway",
      "**Starting small isn't the problem. Waiting forever can be.** You don't need to have a large portfolio before you start learning about investing. You don't need to predict the market. You don't need to invest thousands of dollars every month. Start with an amount that makes sense for you. Contribute consistently. Keep learning. Track your progress. And give your investments time.",
      "**Start Small. Grow Big. Build Your Investment Future.**",
      "## MapleSheet Beginner Investor Checklist",
      "Before you begin, ask yourself: Do I understand what I'm investing in? Do I have money available for long-term investing? Have I chosen an appropriate account? Do I understand my contribution limits? Have I chosen a brokerage that fits my needs? Can I make regular contributions? Am I prepared for market declines? Am I tracking my investments? Am I investing according to my long-term goals?",
      "If you're ready to begin, start with what you can reasonably afford—and build from there. Your portfolio doesn't have to start big. It just has to start.",
      "**Start Tracking. Stop Guessing.**",
      "---",
      "*This article is for educational purposes only and isn't personalized investment, tax or financial advice. Investment returns aren't guaranteed, and you can lose money when investing.*",
    ],
  },
  {
    type: "article",
    title: "How Much Should You Invest Each Month? A Simple Canadian Guide",
    slug: "how-much-should-you-invest-each-month",
    image: "/resources/how-much-should-you-invest-each-month.jpg",
    date: "2026-09-07",
    summary: "You don't need to invest thousands of dollars to get started. Here's how to find a monthly amount that fits your income, goals, and financial situation.",
    body: [
      "One of the most common questions new investors ask is: \"How much should I invest every month?\" You may see people online investing $1,000, $2,000, or even more every month and wonder if you're falling behind. The truth is, there isn't one monthly investment amount that's right for everyone. A person earning $50,000 a year shouldn't necessarily have the same investment target as someone earning $150,000. Your monthly investment amount should fit your income, expenses, debt, emergency savings, goals, and timeline. For a beginner, the best amount may simply be the amount you can invest consistently without putting your day-to-day finances under pressure.",
      "## 1. Start With Your Cash Flow",
      "Before deciding how much to invest, understand where your money is going. Start with: monthly take-home income, minus essential expenses, minus debt payments, minus savings, equals money available for investing and discretionary spending.",
      "For example:",
      "| Monthly Cash Flow | Amount |\n|---|---|\n| Take-home income | $4,000 |\n| Housing & utilities | −$1,800 |\n| Food | −$600 |\n| Transportation | −$400 |\n| Debt payments | −$300 |\n| Other expenses | −$500 |\n| **Remaining** | **$400** |",
      "If you have only $400 left after your regular expenses, investing $1,000 per month isn't realistic. You might instead start with $100 or $150 per month and increase it later. The goal is to create a contribution that you can actually maintain.",
      "## 2. Don't Invest Money You Need for Tomorrow",
      "Investing is generally intended for money that you won't need in the immediate future. If you know you'll need $3,000 next month for a major expense, putting that money into a volatile investment isn't necessarily appropriate. Before aggressively investing, consider whether you have enough money available for unexpected expenses, upcoming bills, short-term goals, and emergency needs. Your financial foundation matters. A portfolio can be growing while your overall financial situation is still under pressure if you're carrying expensive debt or have no emergency savings.",
      "## 3. What Percentage of Your Income Should You Invest?",
      "You'll often hear rules such as \"Invest 10% of your income,\" or \"Invest 15%,\" or \"Invest 20%.\" These can be useful starting points, but they aren't universal rules.",
      "For someone earning $3,000 per month: 10% = $300/month, 15% = $450/month, 20% = $600/month.",
      "For someone earning $5,000 per month: 10% = $500/month, 15% = $750/month, 20% = $1,000/month.",
      "The percentage is simply a framework. Your actual number should reflect your circumstances.",
      "## 4. If You're Starting From Zero, Start Small",
      "Let's say you're new to investing and have never invested before. You don't need to suddenly commit 20% of your income. You could start with $25/month, $50/month, or $100/month. The purpose of starting small isn't to stay small forever. It's to build the habit. Once investing becomes part of your monthly routine, you can gradually increase your contribution. For example: Year 1: $100/month, Year 2: $150/month, Year 3: $200/month, Year 4: $250/month. Your income may also increase over time, giving you more room to invest.",
      "## 5. What Can $100 a Month Become?",
      "Here's where compound growth becomes important. Suppose you invest $100 per month for 30 years. Your total contributions would be $36,000. Now imagine, purely as an illustration, that your investments produced an average annual return of 7%, compounded monthly. The resulting value would be approximately $122,000 — more than three times the amount you personally contributed. The difference comes from hypothetical investment growth.",
      "**But remember: 7% is not guaranteed.** Real investment returns fluctuate, and actual results could be significantly different. The purpose of the example is to demonstrate the potential effect of consistent contributions + time + compounding.",
      "## 6. What If You Invest $250 a Month?",
      "$250/month over 30 years means $90,000 contributed. At the same hypothetical 7% annual return: ~$305,000. Again, this is only an illustration. The important lesson isn't that you'll necessarily earn 7%. It's that increasing your monthly contribution can have a significant effect over a long period.",
      "## 7. What If You Invest $500 a Month?",
      "$500/month for 30 years means your contributions total $180,000. At a hypothetical 7% annual return: ~$610,000. Compare that with the $100/month example.",
      "| Monthly Investment | 30-Year Contributions | Hypothetical 7% Value |\n|---|---|---|\n| $100 | $36,000 | ~$122,000 |\n| $250 | $90,000 | ~$305,000 |\n| $500 | $180,000 | ~$610,000 |\n| $1,000 | $360,000 | ~$1.22M |",
      "*Illustration assumes monthly contributions and a constant 7% annual return. It does not account for taxes, fees, inflation, or changing market returns. Actual results will vary.*",
      "This is why your monthly contribution rate matters. But there's another important lesson: **don't compare your starting point with someone else's finished portfolio.**",
      "## 8. Your Best Monthly Amount Is the Amount You Can Sustain",
      "Imagine two investors. **Investor A** invests $1,000 per month for three months, then financial pressure forces them to stop. **Investor B** invests $150 every month for ten years. Investor B has created a much more sustainable system. Consistency matters. A smaller contribution that you can maintain for years may be more useful than an aggressive contribution that you abandon after a few months.",
      "## 9. Give Yourself a Contribution Goal",
      "Instead of asking \"What's the perfect amount?\" try setting three levels:",
      "- **Minimum** — the amount you can invest even during a difficult month. Example: $50.\n- **Target** — the amount you'd like to invest during a normal month. Example: $150.\n- **Stretch** — the amount you could invest when you have additional income. Example: $300.",
      "This creates flexibility. You don't have to feel like you've failed if you can't invest your stretch amount every month.",
      "## 10. Use Your Paycheque to Build the Habit",
      "One of the easiest ways to make investing consistent is to connect your contribution to your income. For example: every payday → invest $50. If you're paid twice a month: $50 × 2 = $100/month. If you're paid biweekly: $50 × 26 = $1,300/year. You don't have to remember to invest every month. You're turning investing into a routine. This approach also fits naturally with dollar-cost averaging, which we discussed in our previous MapleSheet article.",
      "## 11. Increase Your Investment When Your Income Increases",
      "Here's a simple strategy: every time your income increases, increase your investment contribution. For example, you currently invest $150/month. You receive a raise. Instead of spending all of the additional income, you might increase your investment to $175/month. Later, $200/month. Then $250/month. This is sometimes easier than trying to make a huge investment commitment immediately. You're allowing your investment contribution to grow alongside your income.",
      "## 12. What About TFSA, RRSP and FHSA?",
      "For Canadian investors, where you invest can be just as important as how much you invest. Depending on your circumstances, you might invest through accounts such as a TFSA, RRSP, FHSA, RESP, or non-registered account. These accounts have different rules and purposes. For example, a TFSA allows eligible investments to grow tax-free, and withdrawals generally don't create taxable income. However, withdrawals generally only create new contribution room beginning the following calendar year. Your available TFSA contribution room also depends on your individual history. So don't simply assume \"the annual limit is $7,000, therefore I can contribute $7,000.\" Your personal room may be different. Track your contributions and withdrawals.",
      "## 13. What About Investing Through Wealthsimple or Questrade?",
      "Once you've decided how much you're comfortable investing, you'll need a brokerage or investment platform. I personally use both [Wealthsimple](https://wealthsimple.com/invite/R7ENSA) and [Questrade](https://www.questrade.com) (code: 786314335499127) as part of my own investing journey. They're two examples of Canadian platforms that DIY investors can research.",
      "**Wealthsimple** — You can research [Wealthsimple](https://wealthsimple.com/invite/R7ENSA) if you're looking for a straightforward Canadian investing platform.",
      "**Questrade** — You can also research [Questrade](https://www.questrade.com) (code: 786314335499127) as another option for self-directed investing.",
      "The important thing is to compare the platforms yourself. Consider: account types, investment choices, trading costs, foreign-exchange costs, features, customer support, ease of use, your own investing strategy. **MapleSheet does not recommend that every investor use one particular brokerage.** They're simply platforms I personally use and examples for readers to research.",
      "### Referral Disclosure",
      "Some of the links in this article may be referral links. If you open an account through one of my referral links, MapleSheet Co. may receive a referral benefit at no additional cost to you. This does not mean the platform is right for everyone. Please review the brokerage's current terms and make your own decision.",
      "## 14. Don't Forget to Track Your Contributions",
      "This is where the monthly investing strategy connects directly with MapleSheet. If you decide \"$200 every month,\" track it.",
      "| Month | Contribution | Cumulative Contributions |\n|---|---|---|\n| January | $200 | $200 |\n| February | $200 | $400 |\n| March | $200 | $600 |\n| April | $200 | $800 |\n| May | $200 | $1,000 |\n| June | $200 | $1,200 |",
      "Now you can see your progress. And at the end of the year: $200 × 12 = $2,400. That's $2,400 invested that might not have been invested if you simply waited for the \"right time.\"",
      "## 15. Track More Than Your Monthly Contribution",
      "Your contribution is only the beginning. A good investment tracker should help you understand: contributions (how much money you've added), portfolio value (what your investments are worth), investment growth (how much your investments have gained or lost), dividends (how much investment income you've received), holdings (what you actually own), average cost (what you've paid for your investments), ACB (particularly important for taxable investments), account (whether the investment is in your TFSA, RRSP, FHSA, RESP or non-registered account), and goal (what you're investing toward). That's much more useful than simply knowing your account balance.",
      "## 16. What If You Can't Invest This Month?",
      "Life happens. You may have a car repair, medical expenses, home repairs, higher bills, job changes, or family expenses. Don't let one missed contribution convince you that you've failed. The goal is to build a long-term system, not a perfect record. If you can't invest $300 this month, maybe you invest $50. If you can't invest anything, focus on getting your finances stable and resume your plan when you can.",
      "## 17. Don't Sacrifice Your Financial Stability to Invest More",
      "This is perhaps the most important point in this entire article. **Investing is not supposed to make your financial life worse.** If investing $500 per month means you can't pay your bills, you're investing too much. If you have expensive high-interest debt, paying down that debt may deserve priority. If you have no emergency savings, building a financial cushion may be more appropriate before aggressively increasing investment contributions. There's no prize for having the biggest monthly investment amount. The goal is financial progress.",
      "## 18. A Simple Monthly Investment Formula",
      "1. Calculate your monthly take-home income.\n2. Subtract essential expenses.\n3. Subtract minimum debt payments.\n4. Set aside appropriate savings for your financial situation.\n5. Determine what's realistically available for investing.\n6. Choose a contribution amount you can sustain.\n7. Automate it where appropriate.\n8. Track it.\n9. Review your contribution once or twice a year.\n10. Increase it when your financial situation allows.",
      "Simple.",
      "## 19. The $100 Starting Point",
      "If you're still unsure where to begin, here's my suggestion: start with $100. Not because $100 is some magical number. But because it's small enough for many people to consider manageable while still creating a real investing habit. Then make your next goal: $100 → $150 → $200 → $250. You don't need to jump from $100 to $1,000. Build the habit first. Then build the contribution.",
      "## Your Monthly Investing Plan",
      "Here's a simple template you can use:",
      "**Monthly income:** $________",
      "**Essential expenses:** $________",
      "**Debt payments:** $________",
      "**Savings:** $________",
      "**Available for investing:** $________",
      "**My minimum investment:** $________",
      "**My target investment:** $________",
      "**My stretch investment:** $________",
      "**Investment account:** __________",
      "**Brokerage:** __________",
      "**Investment goal:** __________",
      "**Monthly review date:** __________",
      "Now you've turned a vague idea—\"I should invest more\"—into an actual plan.",
      "## MapleSheet Takeaway",
      "You don't need to invest the same amount as the person next to you. You don't need to invest $1,000 every month. You don't need to wait until you have a large amount of money. You need a number that fits your life. Maybe that's $25. Maybe $100. Maybe $500. The important thing is to start with an amount you can maintain, increase it when your financial situation improves, and track your progress along the way. Small contributions can become meaningful when you give them time.",
      "And remember: start small. Stay consistent. Increase gradually. Track everything. That's the MapleSheet approach to building better investing habits.",
      "## Start Your Investing Journey",
      "If you're ready to begin researching a Canadian brokerage, you can explore the platforms I personally use:",
      "[Explore Wealthsimple](https://wealthsimple.com/invite/R7ENSA)",
      "[Explore Questrade](https://www.questrade.com) — use code 786314335499127 when you sign up",
      "And once you start investing, MapleSheet can help you track the journey—from contributions and holdings to dividends, performance, ACB and your overall portfolio progress.",
      "**Stop Guessing. Start Tracking.**",
      "---",
      "*This article is for educational purposes only and isn't personalized investment, tax or financial advice. Investment returns aren't guaranteed, and you can lose money when investing. TFSA, RRSP, FHSA and other registered-account rules can change, so verify your personal contribution room and applicable rules with the CRA or a qualified professional.*",
    ],
  },
  {
    type: "article",
    title: "Dollar-Cost Averaging Explained: Does Investing a Little at a Time Really Work?",
    slug: "dollar-cost-averaging-explained",
    image: "/resources/dollar-cost-averaging.jpg",
    date: "2026-09-14",
    summary: "A simple Canadian guide to investing consistently without trying to predict the perfect time to enter the market.",
    body: [
      "One of the hardest parts of investing isn't deciding what to buy. It's deciding when to buy it.",
      "Is today a good time? Should you wait for the market to fall? What if you invest today and the market drops tomorrow? What if you wait and the market keeps going up?",
      "These questions can leave beginners sitting on the sidelines for months—or even years.",
      "There's another approach that can make the process simpler: **Dollar-cost averaging, or DCA.**",
      "Instead of trying to find the perfect time to invest, you invest a predetermined amount at regular intervals. For example: $100 every month. The price of your investment will change from month to month, but your contribution stays relatively consistent. You buy more when prices are lower and fewer shares or units when prices are higher. Over time, this can help remove some of the emotion and guesswork from investing.",
      "## What Is Dollar-Cost Averaging?",
      "Dollar-cost averaging is an investing strategy where you invest a predetermined amount of money at regular intervals, regardless of short-term market movements. You don't stop investing simply because the market is down. You don't necessarily increase your contribution because the market is up. You follow your predetermined plan. The result is that you purchase investments at different prices over time.",
      "## A Simple $100 Example",
      "Let's say you decide to invest $100 every month into an investment. Here's a simplified example:",
      "| Month | Investment Price | Amount Invested | Units Purchased |\n|---|---|---|---|\n| January | $10 | $100 | 10.00 |\n| February | $8 | $100 | 12.50 |\n| March | $12 | $100 | 8.33 |\n| April | $10 | $100 | 10.00 |\n| **Total** | | **$400** | **40.83** |",
      "Your average price per unit is approximately: $400 ÷ 40.83 = $9.80",
      "Notice what happened. When the investment price dropped to $8, your $100 bought more units. When the price increased to $12, your $100 bought fewer units. That's one of the basic mechanics behind dollar-cost averaging.",
      "## Why Does DCA Appeal to Beginners?",
      "For many new investors, the biggest advantage isn't necessarily mathematical. It's psychological. Investing a large amount all at once can be intimidating. Imagine you have $10,000 sitting in cash. You invest all of it today. Tomorrow, the market falls 10%. Your investment could now be worth approximately $9,000. Even though nothing fundamentally changed about your long-term goal, seeing that immediate decline can cause anxiety. A DCA approach might instead spread those contributions over time. That doesn't eliminate investment risk, but it can make the process feel more manageable for some investors.",
      "## DCA Doesn't Mean You Avoid Market Declines",
      "This is important. Dollar-cost averaging **doesn't protect you from losses**. If the investment you're buying falls significantly, your portfolio can still decline. DCA simply means that you're continuing to purchase according to your plan. In fact, market declines can mean that your fixed contribution purchases more shares or units.",
      "That's why a DCA investor needs to understand something: falling prices aren't automatically a reason to panic. If you've chosen an investment because you believe it is appropriate for your long-term strategy, temporary market declines may simply be part of the journey. However, if a market decline causes you to realize that you cannot tolerate the investment's risk, that's something you should take seriously.",
      "## DCA vs. Trying to Time the Market",
      "**Investor A — Market Timer:** \"I'll invest when the market falls.\" The problem? You don't know when the bottom will happen. The market could fall 5%. You wait. It falls another 5%. You wait. Then the market suddenly rebounds. Now you wonder: \"Should I buy?\" You can easily end up waiting for a perfect opportunity that never arrives.",
      "**Investor B — Consistent Investor:** \"I'll invest $100 every month.\" Market up? Invest $100. Market down? Invest $100. Market sideways? Invest $100. The strategy doesn't require you to predict tomorrow's market.",
      "## What Happens When the Market Falls?",
      "Suppose you invest $100 per month.",
      "- Month 1, Price = $20 → you buy 5 units\n- Month 2, Price = $10 → you buy 10 units\n- Month 3, Price = $25 → you buy 4 units",
      "Your $100 contribution buys a different number of units each month. When prices are lower, your fixed contribution purchases more. When prices are higher, it purchases less. This is one reason DCA can help investors avoid putting all their money into the market at one specific price.",
      "## But Is DCA Always Better?",
      "No. This is an important distinction. If you already have a large amount of money available to invest, investing it immediately may produce better expected returns than spreading the investment out over time, because the money has more time in the market. Research comparing lump-sum investing with staged investing has generally found that lump-sum investing has a higher expected return over long periods because markets have historically risen more often than they have fallen.",
      "But that doesn't mean lump-sum investing is automatically the best choice for every person. Why? Because investing isn't purely mathematical. **Behavior matters.** If investing your entire $20,000 today causes you to panic and sell when the market falls, a more gradual approach might help you stay invested. A strategy you can actually stick with can be more useful than a theoretically optimal strategy that you abandon.",
      "## DCA and Your Paycheque",
      "One of the easiest ways to implement DCA is through regular income. Imagine you're paid every two weeks. You decide $50 from every paycheque goes toward investing. There are approximately 26 biweekly pay periods in a year. That's $50 × 26 = $1,300 per year — without needing to make a large investment decision every month. You could increase that amount later, for example $50 → $75 → $100 per paycheque as your financial situation improves.",
      "## What If You Can Only Invest $25?",
      "That's okay. DCA isn't about having a large amount of money. It is about regularity. You could invest $25/week (approximately $1,300/year), or $50/week (approximately $2,600/year), or $100/month (approximately $1,200/year). The best amount is the amount that fits your financial situation and can be maintained over time.",
      "## DCA Can Help Remove Emotion From Investing",
      "Investors are human. That means emotions can influence decisions. When markets rise: \"I should buy more before it goes even higher!\" When markets fall: \"I need to sell before it gets worse!\" This cycle can lead investors to buy when prices are high and sell when prices are low. A predetermined contribution plan can help create discipline. Instead of asking \"What should I do today?\" you've already established: \"This is my investing plan.\" That doesn't mean you should blindly continue forever. You should still review your investments and make sure they remain appropriate for your goals.",
      "## DCA Is Not a Guarantee of Profit",
      "Let's make this very clear. Dollar-cost averaging:\n- Doesn't guarantee profits\n- Doesn't prevent losses\n- Doesn't predict market bottoms\n- Doesn't make a bad investment good\n- Doesn't eliminate market risk",
      "What it can potentially do is create consistency, reduce the pressure of timing the market, help investors build a long-term habit, allow fixed contributions to purchase more when prices are lower, and make investing easier to automate.",
      "## What Should You DCA Into?",
      "This is where beginners need to be careful. DCA is a **method of investing**, not an investment itself. You still need to decide what you're buying. That could potentially include broad-market ETFs, individual stocks, bonds, mutual funds, or other investments appropriate to your strategy. But DCA doesn't magically make a risky investment safe. If you continuously invest into a company that eventually fails, buying it every month doesn't solve the underlying problem. Your investment selection still matters.",
      "## DCA With a TFSA",
      "For Canadian investors, a TFSA can be one account where a long-term DCA strategy may be used. For example: January $100, February $100, March $100, April $100, and so on. But remember: your TFSA contribution room is personal. Don't assume that because the annual TFSA dollar limit is a certain amount, you automatically have that much available. Your room depends on factors such as your age/eligibility, previous contributions, unused room and withdrawals. And if you withdraw money from your TFSA, that withdrawn amount generally becomes available as new contribution room on **January 1 of the following year**, not immediately. That's why tracking your contributions is important.",
      "## DCA With Wealthsimple or Questrade",
      "This strategy can also be implemented through a brokerage account. I personally use both [Wealthsimple](https://wealthsimple.com/invite/R7ENSA) and [Questrade](https://www.questrade.com) (code: 786314335499127) as part of my own investing journey. Both are examples of Canadian platforms that DIY investors can research. The important thing is to choose a platform based on your own needs. Consider: account availability, trading costs, investment selection, foreign-exchange costs, automation features, research tools, customer support, overall usability. **Don't choose a brokerage simply because someone recommends it online.** Do your own research.",
      "### MapleSheet Referral Disclosure",
      "Some links in our articles may be referral links. If you open an account through a MapleSheet referral link, MapleSheet Co. may receive a referral benefit at no additional cost to you. We mention [Wealthsimple](https://wealthsimple.com/invite/R7ENSA) and [Questrade](https://www.questrade.com) (code: 786314335499127) because they are platforms we personally use and because they can be useful options for Canadian DIY investors to research. This is not a recommendation that either platform is right for everyone.",
      "## The Importance of Tracking Your DCA Strategy",
      "Here's something many beginners overlook. If you're investing every month, you should know: How much have I invested? What did I buy? How many shares or units do I own? What's my average cost? How much dividend income have I received? How much has my portfolio gained or lost? How much room do I have in my registered accounts? This is especially important once you have multiple accounts or brokerages. For example, you might eventually have a [Wealthsimple](https://wealthsimple.com/invite/R7ENSA) TFSA, a [Questrade](https://www.questrade.com) (code: 786314335499127) RRSP, an FHSA, and a non-registered account. Trying to remember everything manually can become difficult. That's where a portfolio tracker can help.",
      "## DCA + MapleSheet",
      "This is one of the reasons we built MapleSheet. Your brokerage is where you execute your investments. MapleSheet helps you organize and understand your investment journey. You can track things such as contributions, holdings, purchase prices, dividends, portfolio performance, ACB, account types, investment income, portfolio allocation, and progress over time. Instead of simply asking \"How much is my portfolio worth?\" you can start asking better questions: \"How much have I contributed?\" \"How much of my growth came from investment returns?\" \"How much dividend income am I generating?\" \"What's my average cost?\" \"Am I staying consistent with my investment plan?\" That's the difference between simply owning investments and actually understanding your portfolio.",
      "## A Simple DCA Plan for a Beginner",
      "- **Investment amount:** $100/month\n- **Frequency:** Every month\n- **Account:** TFSA\n- **Brokerage:** [Wealthsimple](https://wealthsimple.com/invite/R7ENSA) or [Questrade](https://www.questrade.com) (code: 786314335499127)\n- **Investment:** A diversified investment appropriate for your goals and risk tolerance\n- **Tracking:** MapleSheet\n- **Review:** Every 3–6 months",
      "The goal isn't to constantly change your strategy. It's to establish a system you can follow.",
      "## What Happens When Your Income Increases?",
      "This is where DCA becomes even more powerful. Suppose you start with $100/month. Then you receive a raise. You increase your contribution to $150/month. Later, $200/month. Then $300/month. You're essentially allowing your investment strategy to grow alongside your income. You don't have to start big. You can grow into a bigger investor.",
      "## The Biggest Advantage of DCA May Be Discipline",
      "There's an interesting lesson here. The biggest benefit of dollar-cost averaging may not be that it produces a magical mathematical advantage. It doesn't. The real advantage for many people is that it creates a repeatable behavior. You decide how much you're going to invest. You establish a schedule. You automate it where appropriate. You continue learning. You track your progress. And you give your investments time. That's a powerful combination.",
      "## Final Takeaway",
      "Does investing a little at a time work? It can. But DCA isn't magic. It doesn't guarantee profits. It doesn't eliminate risk. And it doesn't guarantee that you'll outperform someone who invests a lump sum. What it can do is give you a simple, repeatable framework for investing consistently without requiring you to predict what the market will do tomorrow. For a beginner, that can be incredibly valuable. You don't need to wait for the perfect market. You don't need to predict the next crash. You don't need to invest thousands of dollars at once. You can start with $25, $50, $100. Then repeat. Invest. Track. Learn. Adjust. Repeat. Over time, your contributions can grow, your knowledge can grow, and—if your investments perform well—your portfolio can potentially grow alongside them.",
      "## MapleSheet's DCA Checklist",
      "Before you start a dollar-cost averaging strategy, ask yourself: Do I have money available to invest? Do I understand the investment I'm buying? Does it fit my risk tolerance and time horizon? Have I chosen an appropriate account? Have I decided how much I can invest consistently? Can I automate my contributions? Am I tracking my investments? Do I understand my contribution limits? Am I prepared for market declines? Am I thinking long term? If you can answer these questions, you're already moving beyond simply \"buying stocks\" and toward building an actual investing process.",
      "## Start Small. Stay Consistent. Track Everything.",
      "Dollar-cost averaging isn't about finding the perfect day to invest. It's about creating a system that helps you keep investing through many different market conditions. And that's exactly what MapleSheet is designed to help you do: track your money, understand your investments, build better investing habits.",
      "MapleSheet Co. — Helping Canadian DIY investors make sense of their numbers.",
      "---",
      "*This article is for educational purposes only and isn't personalized investment, tax or financial advice. Investment returns aren't guaranteed, and you can lose money when investing. TFSA rules can change, so verify your personal contribution room and applicable rules with the CRA or a qualified professional.*",
    ],
  },
  // ─── LIVE ARTICLES ───────────────────────────────────────────────
  {
    type: "article",
    title: "TFSA Contribution Room in 2026: The Complete Guide",
    slug: "tfsa-contribution-room-2026",
    image: "/resources/tfsa-room.jpg",
    date: "2026-07-30",
    summary: "The 2026 TFSA limit, how cumulative room actually adds up, and the withdrawal rule that trips up even experienced investors.",
    body: [
      "The TFSA annual dollar limit for 2026 is $7,000 — the third year in a row it's held at that number after a run of increases. If you've been eligible since the TFSA started in 2009 and have never contributed, your cumulative room now sits at $109,000.",
      "## How contribution room actually adds up",
      "Room isn't just this year's $7,000. It's the sum of every annual limit since the year you turned 18 (or since 2009, whichever is later), plus any amount you've withdrawn in a previous calendar year, minus whatever you've already contributed. Unused room never expires — it carries forward indefinitely, which is exactly why long-time TFSA holders can have six-figure room even if they've barely contributed.",
      "## The withdrawal rule that catches people off guard",
      "Withdrawing money from a TFSA doesn't shrink your lifetime room — but it also doesn't restore it immediately. If you pull out $5,000 this year, that $5,000 gets added back to your room on January 1 of next year, not the same day you withdraw it. Contribute that same $5,000 again before the calendar flips, and you've over-contributed.",
      "## What the over-contribution penalty actually costs",
      "The CRA doesn't give any grace on this one — even $1 over your room triggers it. Under the Income Tax Act, excess TFSA contributions are taxed at 1% of the highest excess amount for every month the overage sits in the account, and that clock keeps running until you either withdraw the excess or new contribution room opens up. Go over by $6,000 in March and not notice until August, and you're looking at six months of 1% charges on that $6,000 — roughly $360, plus whatever else compounds while you sort it out. If it genuinely happened by honest mistake, you can request a cancellation or waiver of the penalty from the CRA, but that's discretionary, not guaranteed.",
      "## The one thing a TFSA doesn't shield you from",
      "TFSAs are tax-free under Canadian law, but the US doesn't recognize them as a retirement account the way it recognizes RRSPs under the Canada-US tax treaty. That means US-listed stocks and ETFs held inside a TFSA still have a 15% US withholding tax deducted from their dividends before the cash ever reaches you — a quiet cost that catches people who assume \"tax-free account\" means tax-free on everything inside it, regardless of what it holds.",
      "## Why this is hard to track by hand",
      "The CRA's own portal often lags behind your actual contributions, especially early in the year — which means the number it shows you isn't always the number you can safely rely on. Between multiple brokerages, withdrawals from prior years, and this year's fresh room, keeping an accurate running total takes more than memory.",
      "That's the exact problem our [TFSA trackers](/trackers) solve — automatic room calculation that accounts for withdrawals, carry-forward, and multiple institutions, so you're never guessing.",
    ],
  },
  {
    type: "article",
    title: "RRSP Deduction Limit vs. Contribution Room: What's the Difference?",
    slug: "rrsp-deduction-limit-vs-contribution-room",
    image: "/resources/rrsp-deduction.jpg",
    date: "2026-07-28",
    summary: "They sound like the same number. They're usually not — and mixing them up is one of the most common RRSP mistakes.",
    body: [
      "Your RRSP contribution room for 2026 is 18% of your 2025 earned income, up to a maximum of $33,810. That's the ceiling the CRA sets on how much new room you earn this year. But the number on your Notice of Assessment — your deduction limit — isn't the same thing, and the difference matters at tax time.",
      "## Contribution room vs. deduction limit",
      "Contribution room is the running total of everything you're allowed to have contributed, ever — this year's new room plus any unused room carried forward from every prior year. Your deduction limit, shown on your CRA Notice of Assessment, is that same figure adjusted for a few extra factors: a pension adjustment if you belong to an employer pension plan, and any contributions you've already made that haven't been deducted yet. For most people without a workplace pension, the two numbers are close. For anyone with a pension plan, they can diverge meaningfully.",
      "## The first-60-days rule",
      "RRSP contributions made in the first 60 days of a calendar year can be applied to either that year or the previous year's tax return — your choice. This is the single most useful piece of RRSP timing flexibility available, and it's also the rule most people forget exists until their accountant asks about it in March.",
      "## What earned income doesn't include",
      "Investment income, capital gains, and pension income don't count toward earned income for RRSP room purposes — only employment, self-employment, and a few other specific categories do. If most of your income comes from investments, your RRSP room may grow slower than you'd expect.",
      "## The $2,000 cushion that isn't really a bonus",
      "The CRA allows a lifetime $2,000 buffer above your deduction limit with no penalty — but it's easy to misread as \"$2,000 of extra room.\" It isn't. Contributions inside that cushion still can't be deducted from your taxable income beyond your actual limit; the buffer just protects you from the 1% monthly over-contribution tax if you accidentally go slightly over. Exceed your limit plus that $2,000 cushion, and the CRA applies a 1% per month penalty on the excess, calculated at the end of each month it remains — and you're required to file a T1-OVP return within 90 days of year-end to report it, or a late-filing penalty stacks on top.",
      "## Two ways to use RRSP room beyond your own retirement",
      "A spousal RRSP lets the higher-income partner contribute using their own deduction limit into an RRSP registered in the lower-income spouse's name — the deduction goes to the contributor, but future withdrawals are taxed to the spouse, which can split retirement income and lower the household's combined tax bill. Separately, the Home Buyers' Plan lets a first-time buyer withdraw up to $60,000 tax-free from their RRSP toward a home purchase, repaid over 15 years starting the second year after the withdrawal — miss a year's minimum repayment and that installment gets added straight to your taxable income instead of quietly rolling forward.",
      "Our [RRSP trackers](/trackers) pull your actual deduction limit as an editable field rather than assuming a flat number, so the tracker matches what your Notice of Assessment actually says — not a generic formula.",
    ],
  },
  {
    type: "article",
    title: "How Adjusted Cost Base (ACB) Works for Canadian Investors",
    slug: "how-acb-works",
    image: "/resources/acb-explained.jpg",
    date: "2026-07-26",
    summary: "The number that determines how much tax you actually owe when you sell — and why most spreadsheets get it wrong.",
    body: [
      "Adjusted cost base, or ACB, is what the CRA uses to figure out your capital gain or loss when you sell an investment. Get it wrong, and you either overpay tax or under-report — neither of which you want to explain in an audit.",
      "## The core formula",
      "ACB is your average cost per share across every purchase of that security, not the price of your most recent buy. Every time you buy more shares of something you already hold, your ACB recalculates as a weighted average of the old and new cost. Sell shares, and your ACB per remaining share stays the same — only the total drops proportionally.",
      "## Capital gains stay at the 50% inclusion rate",
      "For 2026, capital gains are still taxed at the 50% inclusion rate — meaning only half of your gain gets added to your taxable income. A proposed increase to two-thirds on gains above $250,000 was cancelled, so the math investors have used for years still applies. Your gain is simply your sale proceeds minus your ACB, minus any transaction costs, with half of that result taxed at your marginal rate.",
      "## Why this gets complicated fast",
      "Dividend reinvestment plans, stock splits, return-of-capital distributions, and buying the same stock across multiple brokerages all adjust your ACB — and most people's mental math (or a basic spreadsheet) doesn't account for all of it. A single missed adjustment years ago compounds into a wrong number today.",
      "## The superficial loss rule that quietly cancels tax-loss selling",
      "Sell a losing stock to claim the capital loss, then buy it back within 30 days — before or after the sale — and the CRA treats it as a superficial loss under section 54 of the Income Tax Act. The loss gets denied for that year entirely. It isn't gone forever, though: it gets added back onto the ACB of the shares you repurchased, deferring the loss until you eventually sell those shares for good, outside the 61-day window around any future purchase.",
      "## US dollar holdings need converting, not just tracking",
      "If you hold US-listed stocks or ETFs, your ACB has to be recorded in Canadian dollars — using the exchange rate on the actual date of each transaction, not today's rate. Buy the same US stock on three different dates at three different exchange rates, and each purchase converts separately before averaging into your ACB. Skip the conversion and use a single rate for everything, and your reported gain or loss is off, sometimes significantly, purely from currency movement having nothing to do with the stock itself.",
      "This is exactly why our [Margin and multi-brokerage trackers](/trackers) calculate ACB automatically as you log each transaction, instead of asking you to track a running average by hand.",
    ],
  },
  {
    type: "article",
    title: "Welcome to MapleSheet Resources",
    slug: "welcome",
    image: "/resources/welcome.jpg",
    date: "2026-07-22",
    summary: "Learn first. Track smarter. Make better financial decisions.",
    body: [
      "Welcome to the MapleSheet Resources Hub — a growing library of practical, easy-to-understand resources created for Canadian DIY investors.",
      "At MapleSheet Co., we believe you should understand your money before you track it. A spreadsheet or tracker can organize your investments, but knowing what you're tracking, why it matters, and how the Canadian rules work is what helps you make better decisions.",
      "That's why we're building this resource hub alongside our investment trackers and tools — straightforward guides on Canada's most important investment accounts, tax concepts, and personal-finance strategies, without unnecessary jargon.",
      "## What you'll find here",
      "🍁 TFSA — how contribution room works, how withdrawals affect future room, how over-contributions happen, and how to track your available room across different institutions.",
      "💼 RRSP — contribution room, deduction limits, contribution timing, withdrawals, tax deductions, and the rules that can affect your retirement strategy.",
      "🏠 FHSA — how Canada's First Home Savings Account works, including contribution limits, tax deductions, qualifying withdrawals, and how it fits into a first-home savings strategy.",
      "🎓 RESP — the basics of saving for education, including contributions, government grants like the CESG, investment growth, and the different types of withdrawals.",
      "📊 Non-registered & margin investing — adjusted cost base (ACB), capital gains, dividends, investment income, and the record-keeping that comes with taxable investments.",
      "🧮 Investing & portfolio tracking — how to organize your investments, monitor contributions, track dividends, calculate returns, and keep everything in one place.",
      "## Learn the concept, then track it",
      "Reading about TFSA contribution room is useful. Understanding ACB is useful. Learning how RRSP deductions work is useful. But being able to actually track these things in your own financial life is where the knowledge becomes practical.",
      "That's why many of our educational resources connect directly with the MapleSheet trackers we build — we'll show you not just what something means, but how to organize and track it.",
      "## Step-by-step tracker walkthroughs",
      "We also publish walkthroughs for our MapleSheet products so you can get the most out of your tracker — what each section does, how to enter your information, how the calculations work, and how to interpret the numbers on your dashboard. The goal isn't a complicated spreadsheet that requires you to be a spreadsheet expert — it's a clearer picture of your money.",
      "## New resources every week",
      "This hub will keep growing, with new articles on Canadian investing, registered accounts, taxes, portfolio management, and practical investing concepts every DIY investor should understand. We'll also publish videos and walkthroughs for topics that are easier to follow when you can see them in action — new videos land on our YouTube channel first, then get posted here with supporting notes. Read the articles, watch the videos, or explore the trackers — whichever fits how you learn.",
      "## Built for Canadian DIY investors",
      "You don't need to be a financial expert to become more organized and informed about your money. Whether you're starting with your first $100, building your TFSA, contributing to an RRSP, saving for your first home, investing for your children's education, or managing a larger portfolio, our goal is to make the information easier to understand and easier to apply. Investing doesn't have to start with a large amount — it can start with one contribution, one account, and one better decision at a time.",
      "MapleSheet isn't about telling you what to buy or predicting the market. It's about helping you understand, organize, and track your financial journey so you can make decisions with better information. Explore the guides, learn at your own pace, and use the tools that make sense for your situation.",
      "Knowledge first. Tracking second. Better decisions every step of the way. Welcome to MapleSheet Resources.",
    ],
  },
  // Example video post — Lino: replace youtubeId with a real video and set live: true
  {
    type: "video",
    title: "Tracker walkthrough (video coming soon)",
    date: "2026-07-22",
    summary: "Our first walkthrough video will appear here — how to set up your MapleSheet tracker in under 10 minutes.",
    youtubeId: "",
    live: false,
  },
];

export const FAQS = [
  ["Do I need Excel or Google Sheets?", "Google Sheets — which is free with any Google account. No Excel needed, no software to install. You'll receive a link, click 'Make a copy', and the tracker is yours."],
  ["Is this a subscription?", "No. One-time purchase, yours forever. Free updates to the version you bought, and no recurring fees of any kind."],
  ["How do live prices work?", "Trackers use Google's built-in GOOGLEFINANCE function to pull live stock and ETF quotes automatically — CAD and USD, with automatic currency conversion."],
  ["Will it work on my phone?", "Yes — through the free Google Sheets app. The dashboards are designed on desktop but fully usable on mobile."],
  ["Does it handle Canadian tax rules?", "That's the whole point. TFSA contribution room, RRSP deduction limits, FHSA Line 20805, CESG grant tracking, ACB and capital gains with the 50% inclusion rate — built the CRA way."],
  ["What if I need help?", "Email us. Every buyer gets personal support from Lino directly — no bots, no auto-replies."],
  ["What's your refund policy?", "Because these are instant digital downloads, Etsy's digital-goods policy applies — but if something isn't working, contact us first. We fix problems."],
];
